"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

/* ─────────────────────────────────────────────────────────────
   Supported Languages
───────────────────────────────────────────────────────────── */
export type Language =
  | "en" // English
  | "gu" // Gujarati
  | "hi" // Hindi
  | "mr" // Marathi
  | "ta" // Tamil
  | "te" // Telugu
  | "bn" // Bengali
  | "pa" // Punjabi
  | "kn" // Kannada
  | "ml"; // Malayalam

type LanguageContextType = {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: string) => string;
  languages: { code: Language; label: string }[];
};

const LANGUAGE_STORAGE_KEY = "site-language";

/* ─────────────────────────────────────────────────────────────
   Language Options (for dropdown)
───────────────────────────────────────────────────────────── */
export const languageOptions: { code: Language; label: string }[] = [
  { code: "en", label: "English" },
  { code: "gu", label: "ગુજરાતી" },
  { code: "hi", label: "हिन्दी" },
  { code: "mr", label: "मराठी" },
  { code: "ta", label: "தமிழ்" },
  { code: "te", label: "తెలుగు" },
  { code: "bn", label: "বাংলা" },
  { code: "pa", label: "ਪੰਜਾਬੀ" },
  { code: "kn", label: "ಕನ್ನಡ" },
  { code: "ml", label: "മലയാളം" },
];

/* ─────────────────────────────────────────────────────────────
   Context
───────────────────────────────────────────────────────────── */
const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
  languages: languageOptions,
});

export function useLanguage() {
  return useContext(LanguageContext);
}

/* ─────────────────────────────────────────────────────────────
   Provider
───────────────────────────────────────────────────────────── */
export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>("en");

  // Load saved language from localStorage on first mount
  useEffect(() => {
    if (typeof window !== "undefined") {
      const savedLang = localStorage.getItem(LANGUAGE_STORAGE_KEY) as Language | null;
      if (savedLang && languageOptions.some((item) => item.code === savedLang)) {
        setLangState(savedLang);
      }
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    if (typeof window !== "undefined") {
      localStorage.setItem(LANGUAGE_STORAGE_KEY, newLang);
    }
  };

  const t = (key: string): string => {
    const dict = translations[lang] || translations.en;
    return dict[key] ?? translations.en[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, languages: languageOptions }}>
      {children}
    </LanguageContext.Provider>
  );
}

/* ─────────────────────────────────────────────────────────────
   English Base Dictionary (MASTER)
   IMPORTANT:
   - Add all keys here first
   - Other languages can override only the values
───────────────────────────────────────────────────────────── */
const en: Record<string, string> = {
  // Common
  "lang.select": "Select Language",

  // Nav
  "nav.track": "Track Complaint",
  "nav.transparency": "Transparency",
  "nav.raise": "Raise Complaint",
  "nav.notices": "Notices",
  "nav.login": "Staff Login",
  "nav.home": "Home",
  "nav.meetings": "Meetings",
  "nav.works": "Public Works",
  "nav.budget": "Budget",
  "nav.emergency": "Emergency",
  "nav.services": "Services",
  "nav.help": "Help",

  // Hero
  "hero.badge": "Government transparency portal",
  "hero.title1": "Smart Municipal",
  "hero.title2": "Complaint & Control",
  "hero.subtitle":
    "Track complaints, view meetings, and raise issues with full transparency. No login required.",
  "hero.track": "Track Complaint",
  "hero.raise": "Raise Complaint",
  "hero.transparency": "Transparency",

  // Stats
  "stats.heading": "Live transparency stats",
  "stats.total": "Total Complaints",
  "stats.completed": "Completed Works",
  "stats.pending": "Pending Issues",
  "stats.score": "Transparency Score",

  // Features
  "features.heading": "Citizen services",
  "features.subheading": "What you can do",
  "features.desc":
    "No login needed. Track, submit, or view public information anytime.",
  "features.track.title": "Track by ID",
  "features.track.desc":
    "Search by complaint ID and see status: Pending, In Progress, Meeting Scheduled, or Completed.",
  "features.track.cta": "Track Complaint",
  "features.raise.title": "Raise complaint",
  "features.raise.desc":
    "Submit with OTP verification. Add title, description, location, and images — no account required.",
  "features.raise.cta": "Raise Complaint",
  "features.meetings.title": "Public meetings",
  "features.meetings.desc":
    "View meeting summaries, work progress, and approval status in read-only transparency mode.",
  "features.meetings.cta": "View Meetings",

  // Track page
  "track.title": "Track Complaint",
  "track.hero.desc":
    "Enter your complaint ID to see status: Pending, In Progress, Meeting Scheduled, or Completed.",
  "track.card.title": "Search by Complaint ID",
  "track.card.desc":
    "Use the ID you received when you submitted the complaint.",
  "track.placeholder": "e.g. C-1245 or complaint ID",
  "track.button": "Track",
  "track.process": "Complaint process",
  "track.location": "Location",
  "track.category": "Category",
  "track.submitted": "Submitted",
  "track.updated": "Updated",
  "track.step.pending": "Pending",
  "track.step.assigned": "Assigned",
  "track.step.inprogress": "In Progress",
  "track.step.meeting": "Meeting Scheduled",
  "track.step.completed": "Completed",
  "track.step.rejected": "Rejected",

  // Raise complaint
  "raise.title": "Raise complaint (no login)",
  "raise.hero.desc":
    "Verify with OTP, then submit title, description, location, and optional images.",
  "raise.step1.title": "Step 1: Contact",
  "raise.step1.desc": "Enter phone or email to receive OTP",
  "raise.step2.title": "Step 2: Verify OTP",
  "raise.step2.desc": "Enter the 6-digit code sent to you",
  "raise.step3.title": "Step 3: Complaint details",
  "raise.step3.desc": "Fill in the complaint details",
  "raise.label.contact": "Phone or Email",
  "raise.placeholder.contact": "e.g. 9876543210 or email@example.com",
  "raise.btn.sendotp": "Send OTP",
  "raise.label.otp": "OTP",
  "raise.placeholder.otp": "6-digit code",
  "raise.btn.verify": "Verify",
  "raise.btn.change": "Change number/email",
  "raise.label.title": "Title *",
  "raise.placeholder.title": "Brief title",
  "raise.label.desc": "Description *",
  "raise.placeholder.desc": "Describe the issue",
  "raise.label.location": "Location (address or area)",
  "raise.placeholder.location": "e.g. Block A, Main Road",
  "raise.label.category": "Category",
  "raise.label.priority": "Priority",
  "raise.label.images": "Images (optional, max 5)",
  "raise.btn.addimage": "Add image",
  "raise.btn.submit": "Submit complaint",
  "raise.success.title": "Complaint submitted",
  "raise.success.desc": "Save this ID to track your complaint:",
  "raise.success.track": "Track complaint",

  // Notices
  "notices.title": "Notices & Announcements",
  "notices.hero.desc": "Official notices and updates from the municipality.",
  "notices.empty": "No notices at the moment.",
  "notices.error": "Failed to load notices.",
  "notices.viewpdf": "View PDF",

  // Transparency
  "transparency.title": "Transparency Dashboard",
  "transparency.hero.desc":
    "Area-wise and department performance. Public view — no login required.",
  "transparency.stat.total": "Total Complaints",
  "transparency.stat.completed": "Completed",
  "transparency.stat.pending": "Pending",
  "transparency.stat.rate": "Resolution Rate",
  "transparency.chart.title": "Complaints by category (area)",
  "transparency.chart.desc": "Distribution for transparency",
  "transparency.chart.empty": "No data yet",
  "transparency.recent.title": "Recent activity",
  "transparency.recent.desc": "Latest complaint updates",
  "transparency.recent.empty": "No complaints yet.",

  // Footer
  "footer.brand.desc":
    "Smart Municipal Complaint & Meeting Control — bringing transparency and efficient citizen services to your community.",
  "footer.quicklinks": "Quick Links",
  "footer.contact": "Contact Us",
  "footer.hours.title": "Office Hours",
  "footer.hours.weekday": "Mon – Sat: 10:00 AM – 5:00 PM",
  "footer.hours.weekend": "Sunday & Holidays: Closed",
  "footer.holidays": "Holiday Calendar",
  "footer.holiday.note": "Holidays as per State Government orders.",
  "footer.holiday.public": "Public Holiday",
  "footer.holiday.weekly": "Weekly Off",
  "footer.holiday.list": "Holiday List",
  "footer.rights": "All rights reserved.",
  "footer.noauth": "No login required for complaint tracking & submission.",
  "footer.link.home": "Home",
  "footer.link.track": "Track Complaint",
  "footer.link.raise": "Raise Complaint",
  "footer.link.transparency": "Transparency Portal",
  "footer.link.meetings": "Public Meetings",
  "footer.link.notices": "Notices",
  "footer.link.budget": "Budget",
  "footer.link.works": "Public Works",
  "footer.link.rti": "RTI Application",
  "footer.link.feedback": "Feedback",
  "footer.link.emergency": "Emergency",

  // Dashboard
  "dash.dashboard": "Dashboard",
  "dash.complaints": "Complaints",
  "dash.meetings": "Meetings",
  "dash.tasks": "Tasks",
  "dash.bills": "Bills",
  "dash.payments": "Payments",
  "dash.departments": "Departments",
  "dash.staff": "Staff",
  "dash.notifications": "Notifications",
  "dash.reports": "Reports",
  "dash.audit": "Audit Trail",
  "dash.projects": "Work & Projects",
  "dash.notices": "Manage Notices",
  "dash.profile": "Profile",
  "dash.logout": "Logout",
  "dash.search": "Search complaints, tasks, meetings...",
  "dash.notifications.label": "Notifications",
  "dash.switchrole": "Switch role (demo)",
  "dash.myprofile": "My Profile",
};

/* ─────────────────────────────────────────────────────────────
   Gujarati (Full translation)
───────────────────────────────────────────────────────────── */
const gu: Record<string, string> = {
  ...en,
  "lang.select": "ભાષા પસંદ કરો",

  // Nav
  "nav.track": "ફરિયાદ ટ્રૅક કરો",
  "nav.transparency": "પારદર્શિતા",
  "nav.raise": "ફરિયાદ નોંધાવો",
  "nav.notices": "સૂચનાઓ",
  "nav.login": "સ્ટાફ લૉગિન",
  "nav.home": "હોમ",
  "nav.meetings": "મીટિંગ્સ",

  // Hero
  "hero.badge": "સરકારી પારદર્શિતા પોર્ટલ",
  "hero.title1": "સ્માર્ટ મ્યુનિસિપલ",
  "hero.title2": "ફરિયાદ અને નિયંત્રણ",
  "hero.subtitle": "ફરિયાદ ટ્રૅક કરો, મીટિંગ જુઓ, અને સંપૂર્ણ પારદર્શિતા સાથે સમસ્યા નોંધાવો. લૉગિન જરૂરી નથી.",
  "hero.track": "ફરિયાદ ટ્રૅક કરો",
  "hero.raise": "ફરિયાદ નોંધાવો",
  "hero.transparency": "પારદર્શિતા",

  // Stats
  "stats.heading": "લાઇવ પારદર્શિતા આંકડા",
  "stats.total": "કુલ ફરિયાદો",
  "stats.completed": "પૂર્ણ થયેલ કામ",
  "stats.pending": "બાકી સમસ્યાઓ",
  "stats.score": "પારદર્શિતા સ્કોર",

  // Features
  "features.heading": "નાગરિક સેવાઓ",
  "features.subheading": "તમે શું કરી શકો",
  "features.desc": "લૉગિન જરૂરી નથી. ગમે ત્યારે ટ્રૅક કરો, સબમિટ કરો, અથવા જાહેર માહિતી જુઓ.",
  "features.track.title": "ID દ્વારા ટ્રૅક કરો",
  "features.track.desc": "ફરિયાદ ID દ્વારા શોધો અને સ્ટેટસ જુઓ: બાકી, પ્રક્રિયામાં, મીટિંગ નિર્ધારિત, અથવા પૂર્ણ.",
  "features.track.cta": "ફરિયાદ ટ્રૅક કરો",
  "features.raise.title": "ફરિયાદ નોંધાવો",
  "features.raise.desc": "OTP ચકાસણી સાથે સબમિટ કરો. શીર્ષક, વર્ણન, સ્થળ અને ફોટો ઉમેરો — ખાતું જરૂરી નથી.",
  "features.raise.cta": "ફરિયાદ નોંધાવો",
  "features.meetings.title": "જાહેર મીટિંગ",
  "features.meetings.desc": "મીટિંગ સારાંશ, કામ પ્રગતિ, અને મંજૂરી સ્ટેટસ રીડ-ઓન્લી પારદર્શિતા મોડમાં જુઓ.",
  "features.meetings.cta": "મીટિંગ જુઓ",

  // Track page
  "track.title": "ફરિયાદ ટ્રૅક કરો",
  "track.hero.desc": "વર્તમાન સ્ટેટસ જોવા ફરિયાદ ID દાખલ કરો: બાકી, પ્રક્રિયામાં, મીટિંગ નિર્ધારિત, અથવા પૂર્ણ.",
  "track.card.title": "ફરિયાદ ID દ્વારા શોધો",
  "track.card.desc": "ફરિયાદ સબમિટ કર્યા ત્યારે મળેલ ID વાપરો.",
  "track.placeholder": "દા.ત. C-1245 અથવા ફરિયાદ ID",
  "track.button": "ટ્રૅક કરો",
  "track.process": "ફરિયાદ પ્રક્રિયા",
  "track.location": "સ્થળ",
  "track.category": "શ્રેણી",
  "track.submitted": "સબમિટ",
  "track.updated": "અપડેટ",
  "track.step.pending": "બાકી",
  "track.step.assigned": "સોંપાયેલ",
  "track.step.inprogress": "પ્રક્રિયામાં",
  "track.step.meeting": "મીટિંગ નિર્ધારિત",
  "track.step.completed": "પૂર્ણ",
  "track.step.rejected": "નકારાયેલ",

  // Raise complaint
  "raise.title": "ફરિયાદ નોંધાવો (લૉગિન વગર)",
  "raise.hero.desc": "OTP ચકાસો, પછી શીર્ષક, વર્ણન, સ્થળ અને વૈકલ્પિક ફોટો સબમિટ કરો.",
  "raise.step1.title": "પગલું ૧: સંપર્ક",
  "raise.step1.desc": "OTP મેળવવા ફોન અથવા ઇ-મેઇલ દાખલ કરો",
  "raise.step2.title": "પગલું ૨: OTP ચકાસો",
  "raise.step2.desc": "તમને મોકલેલ ૬-અંકનો કોડ દાખલ કરો",
  "raise.step3.title": "પગલું ૩: ફરિયાદ વિગત",
  "raise.step3.desc": "ફરિયાદની વિગત ભરો",
  "raise.label.contact": "ફોન અથવા ઇ-મેઇલ",
  "raise.placeholder.contact": "દા.ત. 9876543210 અથવા email@example.com",
  "raise.btn.sendotp": "OTP મોકલો",
  "raise.label.otp": "OTP",
  "raise.placeholder.otp": "૬-અંકનો કોડ",
  "raise.btn.verify": "ચકાસો",
  "raise.btn.change": "નંબર/ઇ-મેઇલ બદલો",
  "raise.label.title": "શીર્ષક *",
  "raise.placeholder.title": "ટૂંકું શીર્ષક",
  "raise.label.desc": "વર્ણન *",
  "raise.placeholder.desc": "સમસ્યા વર્ણવો",
  "raise.label.location": "સ્થળ (સરનામું અથવા વિસ્તાર)",
  "raise.placeholder.location": "દા.ત. બ્લૉક A, મુખ્ય રોડ",
  "raise.label.category": "શ્રેણી",
  "raise.label.priority": "પ્રાથમિકતા",
  "raise.label.images": "ફોટો (વૈકલ્પિક, મહત્તમ ૫)",
  "raise.btn.addimage": "ફોટો ઉમેરો",
  "raise.btn.submit": "ફરિયાદ સબમિટ કરો",
  "raise.success.title": "ફરિયાદ સબમિટ થઈ",
  "raise.success.desc": "ફરિયાદ ટ્રૅક કરવા આ ID સાચવો:",
  "raise.success.track": "ફરિયાદ ટ્રૅક કરો",

  // Notices
  "notices.title": "સૂચનાઓ અને જાહેરાતો",
  "notices.hero.desc": "નગરપાલિકા તરફથી સત્તાવાર સૂચનાઓ અને અપડેટ.",
  "notices.empty": "હાલ કોઈ સૂચના નથી.",
  "notices.error": "સૂચનાઓ લોડ કરવામાં નિષ્ફળ.",
  "notices.viewpdf": "PDF જુઓ",

  // Transparency
  "transparency.title": "પારદર્શિતા ડૅશબોર્ડ",
  "transparency.hero.desc": "વિસ્તાર-વાર અને વિભાગ પ્રદર્શન. જાહેર દૃશ્ય — લૉગિન જરૂરી નથી.",
  "transparency.stat.total": "કુલ ફરિયાદો",
  "transparency.stat.completed": "પૂર્ણ",
  "transparency.stat.pending": "બાકી",
  "transparency.stat.rate": "નિરાકરણ દર",
  "transparency.chart.title": "શ્રેણી (વિસ્તાર) પ્રમાણે ફરિયાદો",
  "transparency.chart.desc": "પારદર્શિતા માટે વિતરણ",
  "transparency.chart.empty": "હજી ડેટા નથી",
  "transparency.recent.title": "તાજેતરની પ્રવૃત્તિ",
  "transparency.recent.desc": "છેલ્લા ફરિયાદ અપડેટ",
  "transparency.recent.empty": "હજી ફરિયાદ નથી.",

  // Footer
  "footer.brand.desc": "સ્માર્ટ મ્યુનિસિપલ ફરિયાદ અને મીટિંગ નિયંત્રણ — તમારા સમુદાયમાં પારદર્શિતા અને કાર્યક્ષમ નાગરિક સેવાઓ.",
  "footer.quicklinks": "ઝડપી લિંક્સ",
  "footer.contact": "અમારો સંપર્ક",
  "footer.hours.title": "ઑફિસ સમય",
  "footer.hours.weekday": "સોમ – શનિ: સવારે ૧૦:૦૦ – સાંજે ૫:૦૦",
  "footer.hours.weekend": "રવિવાર અને રજા: બંધ",
  "footer.holidays": "રજા કૅલેન્ડર",
  "footer.holiday.note": "રાજ્ય સરકારના આદેશ મુજબ રજાઓ.",
  "footer.holiday.public": "જાહેર રજા",
  "footer.holiday.weekly": "સાપ્તાહિક રજા",
  "footer.holiday.list": "રજા યાદી",
  "footer.rights": "સર્વ હક્કો સુરક્ષિત.",
  "footer.noauth": "ફરિયાદ ટ્રૅકિંગ અને સબમિશન માટે લૉગિન જરૂરી નથી.",
  "footer.link.home": "હોમ",
  "footer.link.track": "ફરિયાદ ટ્રૅક કરો",
  "footer.link.raise": "ફરિયાદ નોંધાવો",
  "footer.link.transparency": "પારદર્શિતા પોર્ટલ",
  "footer.link.meetings": "જાહેર મીટિંગ",
  "footer.link.notices": "સૂચનાઓ",

  // Dashboard
  "dash.dashboard": "ડૅશબોર્ડ",
  "dash.complaints": "ફરિયાદો",
  "dash.meetings": "મીટિંગ્સ",
  "dash.tasks": "કાર્યો",
  "dash.bills": "બિલ્સ",
  "dash.payments": "ચૂકવણી",
  "dash.departments": "વિભાગો",
  "dash.staff": "સ્ટાફ",
  "dash.notifications": "સૂચનાઓ",
  "dash.reports": "અહેવાલ",
  "dash.audit": "ઓડિટ",
  "dash.projects": "પ્રોજેક્ટ્સ",
  "dash.notices": "સૂચના વ્યવસ્થાપન",
  "dash.profile": "પ્રોફાઇલ",
  "dash.logout": "લૉગ આઉટ",
  "dash.search": "ફરિયાદ, કાર્ય, મીટિંગ શોધો...",
  "dash.notifications.label": "સૂચનાઓ",
  "dash.switchrole": "ભૂમિકા બદલો (ડેમો)",
  "dash.myprofile": "મારી પ્રોફાઇલ",
};

/* ─────────────────────────────────────────────────────────────
   Other Indian Languages
   Missing keys automatically fallback to English
───────────────────────────────────────────────────────────── */
const hi: Record<string, string> = {
  ...en,
  "lang.select": "भाषा चुनें",

  // Nav
  "nav.home": "होम",
  "nav.track": "शिकायत ट्रैक करें",
  "nav.raise": "शिकायत दर्ज करें",
  "nav.transparency": "पारदर्शिता",
  "nav.notices": "सूचनाएँ",
  "nav.login": "स्टाफ लॉगिन",
  "nav.meetings": "मीटिंग्स",

  // Hero
  "hero.badge": "सरकारी पारदर्शिता पोर्टल",
  "hero.title1": "स्मार्ट म्युनिसिपल",
  "hero.title2": "शिकायत और नियंत्रण",
  "hero.subtitle": "शिकायतें ट्रैक करें, मीटिंग देखें, और पूरी पारदर्शिता के साथ समस्या दर्ज करें। लॉगिन की जरूरत नहीं।",
  "hero.track": "शिकायत ट्रैक करें",
  "hero.raise": "शिकायत दर्ज करें",
  "hero.transparency": "पारदर्शिता",

  // Stats
  "stats.heading": "लाइव पारदर्शिता आँकड़े",
  "stats.total": "कुल शिकायतें",
  "stats.completed": "पूर्ण कार्य",
  "stats.pending": "लंबित समस्याएँ",
  "stats.score": "पारदर्शिता स्कोर",

  // Features
  "features.heading": "नागरिक सेवाएँ",
  "features.subheading": "आप क्या कर सकते हैं",
  "features.desc": "लॉगिन की जरूरत नहीं। कभी भी ट्रैक करें, सबमिट करें, या सार्वजनिक जानकारी देखें।",
  "features.track.title": "ID से ट्रैक करें",
  "features.track.desc": "शिकायत ID से खोजें और स्टेटस देखें: लंबित, प्रक्रिया में, मीटिंग निर्धारित, या पूर्ण।",
  "features.track.cta": "शिकायत ट्रैक करें",
  "features.raise.title": "शिकायत दर्ज करें",
  "features.raise.desc": "OTP सत्यापन के साथ सबमिट करें। शीर्षक, विवरण, स्थान और फ़ोटो जोड़ें — खाता जरूरी नहीं।",
  "features.raise.cta": "शिकायत दर्ज करें",
  "features.meetings.title": "सार्वजनिक मीटिंग",
  "features.meetings.desc": "मीटिंग सारांश, कार्य प्रगति, और अनुमोदन स्टेटस रीड-ओनली पारदर्शिता मोड में देखें।",
  "features.meetings.cta": "मीटिंग देखें",

  // Track page
  "track.title": "शिकायत ट्रैक करें",
  "track.hero.desc": "वर्तमान स्टेटस देखने के लिए शिकायत ID दर्ज करें: लंबित, प्रक्रिया में, मीटिंग निर्धारित, या पूर्ण।",
  "track.card.title": "शिकायत ID से खोजें",
  "track.card.desc": "शिकायत सबमिट करते समय मिली ID का उपयोग करें।",
  "track.placeholder": "जैसे C-1245 या शिकायत ID",
  "track.button": "ट्रैक करें",
  "track.process": "शिकायत प्रक्रिया",
  "track.location": "स्थान",
  "track.category": "श्रेणी",
  "track.submitted": "सबमिट",
  "track.updated": "अपडेट",
  "track.step.pending": "लंबित",
  "track.step.assigned": "सौंपा गया",
  "track.step.inprogress": "प्रक्रिया में",
  "track.step.meeting": "मीटिंग निर्धारित",
  "track.step.completed": "पूर्ण",
  "track.step.rejected": "अस्वीकृत",

  // Raise complaint
  "raise.title": "शिकायत दर्ज करें (बिना लॉगिन)",
  "raise.hero.desc": "OTP सत्यापित करें, फिर शीर्षक, विवरण, स्थान और वैकल्पिक फ़ोटो सबमिट करें।",
  "raise.step1.title": "चरण 1: संपर्क",
  "raise.step1.desc": "OTP प्राप्त करने के लिए फ़ोन या ईमेल दर्ज करें",
  "raise.step2.title": "चरण 2: OTP सत्यापित करें",
  "raise.step2.desc": "आपको भेजा गया 6-अंकीय कोड दर्ज करें",
  "raise.step3.title": "चरण 3: शिकायत विवरण",
  "raise.step3.desc": "शिकायत का विवरण भरें",
  "raise.label.contact": "फ़ोन या ईमेल",
  "raise.placeholder.contact": "जैसे 9876543210 या email@example.com",
  "raise.btn.sendotp": "OTP भेजें",
  "raise.label.otp": "OTP",
  "raise.placeholder.otp": "6-अंकीय कोड",
  "raise.btn.verify": "सत्यापित करें",
  "raise.btn.change": "नंबर/ईमेल बदलें",
  "raise.label.title": "शीर्षक *",
  "raise.placeholder.title": "संक्षिप्त शीर्षक",
  "raise.label.desc": "विवरण *",
  "raise.placeholder.desc": "समस्या का वर्णन करें",
  "raise.label.location": "स्थान (पता या क्षेत्र)",
  "raise.placeholder.location": "जैसे ब्लॉक A, मुख्य सड़क",
  "raise.label.category": "श्रेणी",
  "raise.label.priority": "प्राथमिकता",
  "raise.label.images": "फ़ोटो (वैकल्पिक, अधिकतम 5)",
  "raise.btn.addimage": "फ़ोटो जोड़ें",
  "raise.btn.submit": "शिकायत सबमिट करें",
  "raise.success.title": "शिकायत सबमिट हुई",
  "raise.success.desc": "शिकायत ट्रैक करने के लिए यह ID सहेजें:",
  "raise.success.track": "शिकायत ट्रैक करें",

  // Notices
  "notices.title": "सूचनाएँ और घोषणाएँ",
  "notices.hero.desc": "नगरपालिका की ओर से आधिकारिक सूचनाएँ और अपडेट।",
  "notices.empty": "अभी कोई सूचना नहीं।",
  "notices.error": "सूचनाएँ लोड करने में विफल।",
  "notices.viewpdf": "PDF देखें",

  // Transparency
  "transparency.title": "पारदर्शिता डैशबोर्ड",
  "transparency.hero.desc": "क्षेत्र-वार और विभाग प्रदर्शन। सार्वजनिक दृश्य — लॉगिन जरूरी नहीं।",
  "transparency.stat.total": "कुल शिकायतें",
  "transparency.stat.completed": "पूर्ण",
  "transparency.stat.pending": "लंबित",
  "transparency.stat.rate": "समाधान दर",
  "transparency.chart.title": "श्रेणी (क्षेत्र) के अनुसार शिकायतें",
  "transparency.chart.desc": "पारदर्शिता के लिए वितरण",
  "transparency.chart.empty": "अभी डेटा नहीं",
  "transparency.recent.title": "हालिया गतिविधि",
  "transparency.recent.desc": "नवीनतम शिकायत अपडेट",
  "transparency.recent.empty": "अभी कोई शिकायत नहीं।",

  // Footer
  "footer.brand.desc": "स्मार्ट म्युनिसिपल शिकायत और मीटिंग नियंत्रण — आपके समुदाय में पारदर्शिता और कुशल नागरिक सेवाएँ।",
  "footer.quicklinks": "त्वरित लिंक",
  "footer.contact": "हमसे संपर्क करें",
  "footer.hours.title": "कार्यालय समय",
  "footer.hours.weekday": "सोम – शनि: सुबह 10:00 – शाम 5:00",
  "footer.hours.weekend": "रविवार और छुट्टियाँ: बंद",
  "footer.holidays": "छुट्टी कैलेंडर",
  "footer.holiday.note": "राज्य सरकार के आदेशानुसार छुट्टियाँ।",
  "footer.holiday.public": "सार्वजनिक छुट्टी",
  "footer.holiday.weekly": "साप्ताहिक अवकाश",
  "footer.holiday.list": "छुट्टी सूची",
  "footer.rights": "सर्वाधिकार सुरक्षित।",
  "footer.noauth": "शिकायत ट्रैकिंग और सबमिशन के लिए लॉगिन जरूरी नहीं।",
  "footer.link.home": "होम",
  "footer.link.track": "शिकायत ट्रैक करें",
  "footer.link.raise": "शिकायत दर्ज करें",
  "footer.link.transparency": "पारदर्शिता पोर्टल",
  "footer.link.meetings": "सार्वजनिक मीटिंग",
  "footer.link.notices": "सूचनाएँ",

  // Dashboard
  "dash.dashboard": "डैशबोर्ड",
  "dash.complaints": "शिकायतें",
  "dash.meetings": "मीटिंग्स",
  "dash.tasks": "कार्य",
  "dash.bills": "बिल",
  "dash.payments": "भुगतान",
  "dash.departments": "विभाग",
  "dash.staff": "स्टाफ",
  "dash.notifications": "सूचनाएँ",
  "dash.reports": "रिपोर्ट",
  "dash.audit": "ऑडिट",
  "dash.projects": "परियोजनाएँ",
  "dash.notices": "सूचना प्रबंधन",
  "dash.profile": "प्रोफ़ाइल",
  "dash.logout": "लॉग आउट",
  "dash.search": "शिकायत, कार्य, मीटिंग खोजें...",
  "dash.notifications.label": "सूचनाएँ",
  "dash.switchrole": "भूमिका बदलें (डेमो)",
  "dash.myprofile": "मेरी प्रोफ़ाइल",
};

const mr: Record<string, string> = {
  ...en,
  "lang.select": "भाषा निवडा",

  // Nav
  "nav.home": "मुख्यपृष्ठ",
  "nav.track": "तक्रार ट्रॅक करा",
  "nav.raise": "तक्रार नोंदवा",
  "nav.transparency": "पारदर्शकता",
  "nav.notices": "सूचना",
  "nav.login": "स्टाफ लॉगिन",
  "nav.meetings": "बैठका",

  // Hero
  "hero.badge": "सरकारी पारदर्शकता पोर्टल",
  "hero.title1": "स्मार्ट महानगरपालिका",
  "hero.title2": "तक्रार आणि नियंत्रण",
  "hero.subtitle": "तक्रारी ट्रॅक करा, बैठका पाहा, आणि पूर्ण पारदर्शकतेसह समस्या नोंदवा. लॉगिन आवश्यक नाही.",
  "hero.track": "तक्रार ट्रॅक करा",
  "hero.raise": "तक्रार नोंदवा",
  "hero.transparency": "पारदर्शकता",

  // Stats
  "stats.heading": "लाइव्ह पारदर्शकता आकडेवारी",
  "stats.total": "एकूण तक्रारी",
  "stats.completed": "पूर्ण झालेली कामे",
  "stats.pending": "प्रलंबित समस्या",
  "stats.score": "पारदर्शकता स्कोर",

  // Features
  "features.heading": "नागरिक सेवा",
  "features.subheading": "तुम्ही काय करू शकता",
  "features.desc": "लॉगिन आवश्यक नाही. कधीही ट्रॅक करा, सबमिट करा, किंवा सार्वजनिक माहिती पाहा.",
  "features.track.title": "ID द्वारे ट्रॅक करा",
  "features.track.desc": "तक्रार ID ने शोधा आणि स्थिती पाहा: प्रलंबित, प्रक्रियेत, बैठक निश्चित, किंवा पूर्ण.",
  "features.track.cta": "तक्रार ट्रॅक करा",
  "features.raise.title": "तक्रार नोंदवा",
  "features.raise.desc": "OTP पडताळणीसह सबमिट करा. शीर्षक, वर्णन, स्थान आणि फोटो जोडा — खाते आवश्यक नाही.",
  "features.raise.cta": "तक्रार नोंदवा",
  "features.meetings.title": "सार्वजनिक बैठका",
  "features.meetings.desc": "बैठक सारांश, कार्य प्रगती, आणि मंजुरी स्थिती रीड-ओन्ली पारदर्शकता मोडमध्ये पाहा.",
  "features.meetings.cta": "बैठका पाहा",

  // Track page
  "track.title": "तक्रार ट्रॅक करा",
  "track.hero.desc": "सध्याची स्थिती पाहण्यासाठी तक्रार ID टाका: प्रलंबित, प्रक्रियेत, बैठक निश्चित, किंवा पूर्ण.",
  "track.card.title": "तक्रार ID ने शोधा",
  "track.card.desc": "तक्रार सबमिट केल्यावर मिळालेला ID वापरा.",
  "track.placeholder": "उदा. C-1245 किंवा तक्रार ID",
  "track.button": "ट्रॅक करा",
  "track.process": "तक्रार प्रक्रिया",
  "track.location": "स्थान",
  "track.category": "श्रेणी",
  "track.submitted": "सबमिट",
  "track.updated": "अपडेट",
  "track.step.pending": "प्रलंबित",
  "track.step.assigned": "नियुक्त",
  "track.step.inprogress": "प्रक्रियेत",
  "track.step.meeting": "बैठक निश्चित",
  "track.step.completed": "पूर्ण",
  "track.step.rejected": "नाकारले",

  // Raise complaint
  "raise.title": "तक्रार नोंदवा (लॉगिनशिवाय)",
  "raise.hero.desc": "OTP पडताळा, मग शीर्षक, वर्णन, स्थान आणि पर्यायी फोटो सबमिट करा.",
  "raise.step1.title": "पायरी १: संपर्क",
  "raise.step1.desc": "OTP मिळवण्यासाठी फोन किंवा ईमेल टाका",
  "raise.step2.title": "पायरी २: OTP पडताळा",
  "raise.step2.desc": "तुम्हाला पाठवलेला ६-अंकी कोड टाका",
  "raise.step3.title": "पायरी ३: तक्रार तपशील",
  "raise.step3.desc": "तक्रारीचा तपशील भरा",
  "raise.label.contact": "फोन किंवा ईमेल",
  "raise.placeholder.contact": "उदा. 9876543210 किंवा email@example.com",
  "raise.btn.sendotp": "OTP पाठवा",
  "raise.label.otp": "OTP",
  "raise.placeholder.otp": "६-अंकी कोड",
  "raise.btn.verify": "पडताळा",
  "raise.btn.change": "नंबर/ईमेल बदला",
  "raise.label.title": "शीर्षक *",
  "raise.placeholder.title": "थोडक्यात शीर्षक",
  "raise.label.desc": "वर्णन *",
  "raise.placeholder.desc": "समस्या वर्णन करा",
  "raise.label.location": "स्थान (पत्ता किंवा परिसर)",
  "raise.placeholder.location": "उदा. ब्लॉक A, मुख्य रस्ता",
  "raise.label.category": "श्रेणी",
  "raise.label.priority": "प्राधान्य",
  "raise.label.images": "फोटो (पर्यायी, जास्तीत जास्त ५)",
  "raise.btn.addimage": "फोटो जोडा",
  "raise.btn.submit": "तक्रार सबमिट करा",
  "raise.success.title": "तक्रार सबमिट झाली",
  "raise.success.desc": "तक्रार ट्रॅक करण्यासाठी हा ID जतन करा:",
  "raise.success.track": "तक्रार ट्रॅक करा",

  // Notices
  "notices.title": "सूचना आणि घोषणा",
  "notices.hero.desc": "महानगरपालिकेकडून अधिकृत सूचना आणि अपडेट.",
  "notices.empty": "सध्या कोणतीही सूचना नाही.",
  "notices.error": "सूचना लोड करण्यात अयशस्वी.",
  "notices.viewpdf": "PDF पाहा",

  // Transparency
  "transparency.title": "पारदर्शकता डॅशबोर्ड",
  "transparency.hero.desc": "क्षेत्र-निहाय आणि विभाग कामगिरी. सार्वजनिक दृश्य — लॉगिन आवश्यक नाही.",
  "transparency.stat.total": "एकूण तक्रारी",
  "transparency.stat.completed": "पूर्ण",
  "transparency.stat.pending": "प्रलंबित",
  "transparency.stat.rate": "निराकरण दर",
  "transparency.chart.title": "श्रेणी (क्षेत्र) नुसार तक्रारी",
  "transparency.chart.desc": "पारदर्शकतेसाठी वितरण",
  "transparency.chart.empty": "अद्याप डेटा नाही",
  "transparency.recent.title": "अलीकडील क्रियाकलाप",
  "transparency.recent.desc": "नवीनतम तक्रार अपडेट",
  "transparency.recent.empty": "अद्याप कोणतीही तक्रार नाही.",

  // Footer
  "footer.brand.desc": "स्मार्ट महानगरपालिका तक्रार आणि बैठक नियंत्रण — तुमच्या समुदायात पारदर्शकता आणि कार्यक्षम नागरिक सेवा.",
  "footer.quicklinks": "जलद दुवे",
  "footer.contact": "आमच्याशी संपर्क करा",
  "footer.hours.title": "कार्यालय वेळ",
  "footer.hours.weekday": "सोम – शनि: सकाळी १०:०० – संध्याकाळी ५:००",
  "footer.hours.weekend": "रविवार आणि सुट्ट्या: बंद",
  "footer.holidays": "सुट्टी दिनदर्शिका",
  "footer.holiday.note": "राज्य शासनाच्या आदेशानुसार सुट्ट्या.",
  "footer.holiday.public": "सार्वजनिक सुट्टी",
  "footer.holiday.weekly": "साप्ताहिक सुट्टी",
  "footer.holiday.list": "सुट्टी यादी",
  "footer.rights": "सर्व हक्क राखीव.",
  "footer.noauth": "तक्रार ट्रॅकिंग आणि सबमिशनसाठी लॉगिन आवश्यक नाही.",
  "footer.link.home": "मुख्यपृष्ठ",
  "footer.link.track": "तक्रार ट्रॅक करा",
  "footer.link.raise": "तक्रार नोंदवा",
  "footer.link.transparency": "पारदर्शकता पोर्टल",
  "footer.link.meetings": "सार्वजनिक बैठका",
  "footer.link.notices": "सूचना",

  // Dashboard
  "dash.dashboard": "डॅशबोर्ड",
  "dash.complaints": "तक्रारी",
  "dash.meetings": "बैठका",
  "dash.tasks": "कार्ये",
  "dash.bills": "बिले",
  "dash.payments": "देयके",
  "dash.departments": "विभाग",
  "dash.staff": "कर्मचारी",
  "dash.notifications": "सूचना",
  "dash.reports": "अहवाल",
  "dash.audit": "ऑडिट",
  "dash.projects": "प्रकल्प",
  "dash.notices": "सूचना व्यवस्थापन",
  "dash.profile": "प्रोफाइल",
  "dash.logout": "लॉग आउट",
  "dash.search": "तक्रार, कार्य, बैठक शोधा...",
  "dash.notifications.label": "सूचना",
  "dash.switchrole": "भूमिका बदला (डेमो)",
  "dash.myprofile": "माझी प्रोफाइल",
};

const ta: Record<string, string> = {
  ...en,
  "lang.select": "மொழியைத் தேர்ந்தெடுக்கவும்",

  // Nav
  "nav.home": "முகப்பு",
  "nav.track": "புகாரை கண்காணிக்கவும்",
  "nav.raise": "புகார் அளிக்கவும்",
  "nav.transparency": "வெளிப்படைத்தன்மை",
  "nav.notices": "அறிவிப்புகள்",
  "nav.login": "பணியாளர் உள்நுழைவு",
  "nav.meetings": "கூட்டங்கள்",

  // Hero
  "hero.badge": "அரசு வெளிப்படைத்தன்மை போர்டல்",
  "hero.title1": "ஸ்மார்ட் நகராட்சி",
  "hero.title2": "புகார் மற்றும் கட்டுப்பாடு",
  "hero.subtitle": "புகார்களை கண்காணிக்கவும், கூட்டங்களை பார்க்கவும், முழு வெளிப்படைத்தன்மையுடன் சிக்கல்களை பதிவு செய்யவும். உள்நுழைவு தேவையில்லை.",
  "hero.track": "புகாரை கண்காணிக்கவும்",
  "hero.raise": "புகார் அளிக்கவும்",
  "hero.transparency": "வெளிப்படைத்தன்மை",

  // Stats
  "stats.heading": "நேரடி வெளிப்படைத்தன்மை புள்ளிவிவரங்கள்",
  "stats.total": "மொத்த புகார்கள்",
  "stats.completed": "முடிந்த பணிகள்",
  "stats.pending": "நிலுவையிலுள்ள சிக்கல்கள்",
  "stats.score": "வெளிப்படைத்தன்மை மதிப்பெண்",

  // Features
  "features.heading": "குடிமக்கள் சேவைகள்",
  "features.subheading": "நீங்கள் என்ன செய்யலாம்",
  "features.desc": "உள்நுழைவு தேவையில்லை. எப்போதும் கண்காணிக்கவும், சமர்ப்பிக்கவும், அல்லது பொது தகவல்களை பார்க்கவும்.",
  "features.track.title": "ID மூலம் கண்காணிக்கவும்",
  "features.track.desc": "புகார் ID மூலம் தேடி நிலையை பார்க்கவும்: நிலுவை, செயல்பாட்டில், கூட்டம் திட்டமிடப்பட்டது, அல்லது முடிந்தது.",
  "features.track.cta": "புகாரை கண்காணிக்கவும்",
  "features.raise.title": "புகார் அளிக்கவும்",
  "features.raise.desc": "OTP சரிபார்ப்புடன் சமர்ப்பிக்கவும். தலைப்பு, விளக்கம், இடம் மற்றும் படங்கள் சேர்க்கவும் — கணக்கு தேவையில்லை.",
  "features.raise.cta": "புகார் அளிக்கவும்",
  "features.meetings.title": "பொது கூட்டங்கள்",
  "features.meetings.desc": "கூட்ட சுருக்கங்கள், பணி முன்னேற்றம், மற்றும் ஒப்புதல் நிலையை படிக்க-மட்டும் வெளிப்படைத்தன்மை பயன்முறையில் பார்க்கவும்.",
  "features.meetings.cta": "கூட்டங்களை பார்க்கவும்",

  // Track page
  "track.title": "புகாரை கண்காணிக்கவும்",
  "track.hero.desc": "தற்போதைய நிலையை பார்க்க புகார் ID உள்ளிடவும்: நிலுவை, செயல்பாட்டில், கூட்டம் திட்டமிடப்பட்டது, அல்லது முடிந்தது.",
  "track.card.title": "புகார் ID மூலம் தேடவும்",
  "track.card.desc": "புகார் சமர்ப்பித்தபோது கிடைத்த ID ஐ பயன்படுத்தவும்.",
  "track.placeholder": "எ.கா. C-1245 அல்லது புகார் ID",
  "track.button": "கண்காணிக்கவும்",
  "track.process": "புகார் செயல்முறை",
  "track.location": "இடம்",
  "track.category": "வகை",
  "track.submitted": "சமர்ப்பிக்கப்பட்டது",
  "track.updated": "புதுப்பிக்கப்பட்டது",
  "track.step.pending": "நிலுவை",
  "track.step.assigned": "ஒதுக்கப்பட்டது",
  "track.step.inprogress": "செயல்பாட்டில்",
  "track.step.meeting": "கூட்டம் திட்டமிடப்பட்டது",
  "track.step.completed": "முடிந்தது",
  "track.step.rejected": "நிராகரிக்கப்பட்டது",

  // Raise complaint
  "raise.title": "புகார் அளிக்கவும் (உள்நுழைவு இல்லாமல்)",
  "raise.hero.desc": "OTP சரிபார்க்கவும், பின்னர் தலைப்பு, விளக்கம், இடம் மற்றும் விருப்பமான படங்கள் சமர்ப்பிக்கவும்.",
  "raise.step1.title": "படி 1: தொடர்பு",
  "raise.step1.desc": "OTP பெற தொலைபேசி அல்லது மின்னஞ்சல் உள்ளிடவும்",
  "raise.step2.title": "படி 2: OTP சரிபார்க்கவும்",
  "raise.step2.desc": "உங்களுக்கு அனுப்பப்பட்ட 6-இலக்க குறியீட்டை உள்ளிடவும்",
  "raise.step3.title": "படி 3: புகார் விவரங்கள்",
  "raise.step3.desc": "புகார் விவரங்களை நிரப்பவும்",
  "raise.label.contact": "தொலைபேசி அல்லது மின்னஞ்சல்",
  "raise.placeholder.contact": "எ.கா. 9876543210 அல்லது email@example.com",
  "raise.btn.sendotp": "OTP அனுப்பவும்",
  "raise.label.otp": "OTP",
  "raise.placeholder.otp": "6-இலக்க குறியீடு",
  "raise.btn.verify": "சரிபார்க்கவும்",
  "raise.btn.change": "எண்/மின்னஞ்சல் மாற்றவும்",
  "raise.label.title": "தலைப்பு *",
  "raise.placeholder.title": "சுருக்கமான தலைப்பு",
  "raise.label.desc": "விளக்கம் *",
  "raise.placeholder.desc": "சிக்கலை விவரிக்கவும்",
  "raise.label.location": "இடம் (முகவரி அல்லது பகுதி)",
  "raise.placeholder.location": "எ.கா. தொகுதி A, முக்கிய சாலை",
  "raise.label.category": "வகை",
  "raise.label.priority": "முன்னுரிமை",
  "raise.label.images": "படங்கள் (விருப்பமானது, அதிகபட்சம் 5)",
  "raise.btn.addimage": "படம் சேர்க்கவும்",
  "raise.btn.submit": "புகார் சமர்ப்பிக்கவும்",
  "raise.success.title": "புகார் சமர்ப்பிக்கப்பட்டது",
  "raise.success.desc": "புகாரை கண்காணிக்க இந்த ID ஐ சேமிக்கவும்:",
  "raise.success.track": "புகாரை கண்காணிக்கவும்",

  // Notices
  "notices.title": "அறிவிப்புகள் மற்றும் அறிவிக்கைகள்",
  "notices.hero.desc": "நகராட்சியிலிருந்து அதிகாரப்பூர்வ அறிவிப்புகள் மற்றும் புதுப்பிப்புகள்.",
  "notices.empty": "தற்போது அறிவிப்புகள் இல்லை.",
  "notices.error": "அறிவிப்புகளை ஏற்ற முடியவில்லை.",
  "notices.viewpdf": "PDF பார்க்கவும்",

  // Transparency
  "transparency.title": "வெளிப்படைத்தன்மை டாஷ்போர்டு",
  "transparency.hero.desc": "பகுதி வாரியான மற்றும் துறை செயல்திறன். பொது காட்சி — உள்நுழைவு தேவையில்லை.",
  "transparency.stat.total": "மொத்த புகார்கள்",
  "transparency.stat.completed": "முடிந்தது",
  "transparency.stat.pending": "நிலுவை",
  "transparency.stat.rate": "தீர்வு விகிதம்",
  "transparency.chart.title": "வகை (பகுதி) வாரியான புகார்கள்",
  "transparency.chart.desc": "வெளிப்படைத்தன்மைக்கான விநியோகம்",
  "transparency.chart.empty": "இன்னும் தரவு இல்லை",
  "transparency.recent.title": "சமீபத்திய செயல்பாடு",
  "transparency.recent.desc": "சமீபத்திய புகார் புதுப்பிப்புகள்",
  "transparency.recent.empty": "இன்னும் புகார்கள் இல்லை.",

  // Footer
  "footer.brand.desc": "ஸ்மார்ட் நகராட்சி புகார் மற்றும் கூட்ட கட்டுப்பாடு — உங்கள் சமூகத்தில் வெளிப்படைத்தன்மை மற்றும் திறமையான குடிமக்கள் சேவைகள்.",
  "footer.quicklinks": "விரைவு இணைப்புகள்",
  "footer.contact": "எங்களை தொடர்பு கொள்ளவும்",
  "footer.hours.title": "அலுவலக நேரம்",
  "footer.hours.weekday": "திங்கள் – சனி: காலை 10:00 – மாலை 5:00",
  "footer.hours.weekend": "ஞாயிறு மற்றும் விடுமுறைகள்: மூடப்பட்டது",
  "footer.holidays": "விடுமுறை நாட்காட்டி",
  "footer.holiday.note": "மாநில அரசு உத்தரவுகளின்படி விடுமுறைகள்.",
  "footer.holiday.public": "பொது விடுமுறை",
  "footer.holiday.weekly": "வாராந்திர விடுமுறை",
  "footer.holiday.list": "விடுமுறை பட்டியல்",
  "footer.rights": "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
  "footer.noauth": "புகார் கண்காணிப்பு மற்றும் சமர்ப்பிப்புக்கு உள்நுழைவு தேவையில்லை.",
  "footer.link.home": "முகப்பு",
  "footer.link.track": "புகாரை கண்காணிக்கவும்",
  "footer.link.raise": "புகார் அளிக்கவும்",
  "footer.link.transparency": "வெளிப்படைத்தன்மை போர்டல்",
  "footer.link.meetings": "பொது கூட்டங்கள்",
  "footer.link.notices": "அறிவிப்புகள்",

  // Dashboard
  "dash.dashboard": "டாஷ்போர்டு",
  "dash.complaints": "புகார்கள்",
  "dash.meetings": "கூட்டங்கள்",
  "dash.tasks": "பணிகள்",
  "dash.bills": "பில்கள்",
  "dash.payments": "கொடுப்பனவுகள்",
  "dash.departments": "துறைகள்",
  "dash.staff": "பணியாளர்கள்",
  "dash.notifications": "அறிவிப்புகள்",
  "dash.reports": "அறிக்கைகள்",
  "dash.audit": "தணிக்கை",
  "dash.projects": "திட்டங்கள்",
  "dash.notices": "அறிவிப்பு மேலாண்மை",
  "dash.profile": "சுயவிவரம்",
  "dash.logout": "வெளியேறு",
  "dash.search": "புகார்கள், பணிகள், கூட்டங்கள் தேடவும்...",
  "dash.notifications.label": "அறிவிப்புகள்",
  "dash.switchrole": "பாத்திரம் மாற்றவும் (டெமோ)",
  "dash.myprofile": "என் சுயவிவரம்",
};

const te: Record<string, string> = {
  ...en,
  "lang.select": "భాషను ఎంచుకోండి",

  // Nav
  "nav.home": "హోమ్",
  "nav.track": "ఫిర్యాదు ట్రాక్ చేయండి",
  "nav.raise": "ఫిర్యాదు నమోదు చేయండి",
  "nav.transparency": "పారదర్శకత",
  "nav.notices": "నోటీసులు",
  "nav.login": "సిబ్బంది లాగిన్",
  "nav.meetings": "సమావేశాలు",

  // Hero
  "hero.badge": "ప్రభుత్వ పారదర్శకత పోర్టల్",
  "hero.title1": "స్మార్ట్ మునిసిపల్",
  "hero.title2": "ఫిర్యాదు మరియు నియంత్రణ",
  "hero.subtitle": "ఫిర్యాదులను ట్రాక్ చేయండి, సమావేశాలు చూడండి, మరియు పూర్తి పారదర్శకతతో సమస్యలు నమోదు చేయండి. లాగిన్ అవసరం లేదు.",
  "hero.track": "ఫిర్యాదు ట్రాక్ చేయండి",
  "hero.raise": "ఫిర్యాదు నమోదు చేయండి",
  "hero.transparency": "పారదర్శకత",

  // Stats
  "stats.heading": "లైవ్ పారదర్శకత గణాంకాలు",
  "stats.total": "మొత్తం ఫిర్యాదులు",
  "stats.completed": "పూర్తయిన పనులు",
  "stats.pending": "పెండింగ్ సమస్యలు",
  "stats.score": "పారదర్శకత స్కోర్",

  // Features
  "features.heading": "పౌర సేవలు",
  "features.subheading": "మీరు ఏమి చేయవచ్చు",
  "features.desc": "లాగిన్ అవసరం లేదు. ఎప్పుడైనా ట్రాక్ చేయండి, సమర్పించండి, లేదా పబ్లిక్ సమాచారం చూడండి.",
  "features.track.title": "ID ద్వారా ట్రాక్ చేయండి",
  "features.track.desc": "ఫిర్యాదు ID ద్వారా వెతకండి మరియు స్థితి చూడండి: పెండింగ్, ప్రక్రియలో, సమావేశం నిర్ణయించబడింది, లేదా పూర్తయింది.",
  "features.track.cta": "ఫిర్యాదు ట్రాక్ చేయండి",
  "features.raise.title": "ఫిర్యాదు నమోదు చేయండి",
  "features.raise.desc": "OTP ధృవీకరణతో సమర్పించండి. శీర్షిక, వివరణ, స్థానం మరియు చిత్రాలు జోడించండి — ఖాతా అవసరం లేదు.",
  "features.raise.cta": "ఫిర్యాదు నమోదు చేయండి",
  "features.meetings.title": "పబ్లిక్ సమావేశాలు",
  "features.meetings.desc": "సమావేశ సారాంశాలు, పని పురోగతి, మరియు ఆమోద స్థితిని రీడ్-ఓన్లీ పారదర్శకత మోడ్‌లో చూడండి.",
  "features.meetings.cta": "సమావేశాలు చూడండి",

  // Track page
  "track.title": "ఫిర్యాదు ట్రాక్ చేయండి",
  "track.hero.desc": "ప్రస్తుత స్థితి చూడటానికి ఫిర్యాదు ID నమోదు చేయండి: పెండింగ్, ప్రక్రియలో, సమావేశం నిర్ణయించబడింది, లేదా పూర్తయింది.",
  "track.card.title": "ఫిర్యాదు ID ద్వారా వెతకండి",
  "track.card.desc": "ఫిర్యాదు సమర్పించినప్పుడు అందిన ID ఉపయోగించండి.",
  "track.placeholder": "ఉదా. C-1245 లేదా ఫిర్యాదు ID",
  "track.button": "ట్రాక్ చేయండి",
  "track.process": "ఫిర్యాదు ప్రక్రియ",
  "track.location": "స్థానం",
  "track.category": "వర్గం",
  "track.submitted": "సమర్పించబడింది",
  "track.updated": "నవీకరించబడింది",
  "track.step.pending": "పెండింగ్",
  "track.step.assigned": "కేటాయించబడింది",
  "track.step.inprogress": "ప్రక్రియలో",
  "track.step.meeting": "సమావేశం నిర్ణయించబడింది",
  "track.step.completed": "పూర్తయింది",
  "track.step.rejected": "తిరస్కరించబడింది",

  // Raise complaint
  "raise.title": "ఫిర్యాదు నమోదు చేయండి (లాగిన్ లేకుండా)",
  "raise.hero.desc": "OTP ధృవీకరించండి, తర్వాత శీర్షిక, వివరణ, స్థానం మరియు ఐచ్ఛిక చిత్రాలు సమర్పించండి.",
  "raise.step1.title": "దశ 1: సంప్రదింపు",
  "raise.step1.desc": "OTP పొందడానికి ఫోన్ లేదా ఇమెయిల్ నమోదు చేయండి",
  "raise.step2.title": "దశ 2: OTP ధృవీకరించండి",
  "raise.step2.desc": "మీకు పంపిన 6-అంకెల కోడ్ నమోదు చేయండి",
  "raise.step3.title": "దశ 3: ఫిర్యాదు వివరాలు",
  "raise.step3.desc": "ఫిర్యాదు వివరాలు నింపండి",
  "raise.label.contact": "ఫోన్ లేదా ఇమెయిల్",
  "raise.placeholder.contact": "ఉదా. 9876543210 లేదా email@example.com",
  "raise.btn.sendotp": "OTP పంపండి",
  "raise.label.otp": "OTP",
  "raise.placeholder.otp": "6-అంకెల కోడ్",
  "raise.btn.verify": "ధృవీకరించండి",
  "raise.btn.change": "నంబర్/ఇమెయిల్ మార్చండి",
  "raise.label.title": "శీర్షిక *",
  "raise.placeholder.title": "సంక్షిప్త శీర్షిక",
  "raise.label.desc": "వివరణ *",
  "raise.placeholder.desc": "సమస్యను వివరించండి",
  "raise.label.location": "స్థానం (చిరునామా లేదా ప్రాంతం)",
  "raise.placeholder.location": "ఉదా. బ్లాక్ A, మెయిన్ రోడ్",
  "raise.label.category": "వర్గం",
  "raise.label.priority": "ప్రాధాన్యత",
  "raise.label.images": "చిత్రాలు (ఐచ్ఛికం, గరిష్టం 5)",
  "raise.btn.addimage": "చిత్రం జోడించండి",
  "raise.btn.submit": "ఫిర్యాదు సమర్పించండి",
  "raise.success.title": "ఫిర్యాదు సమర్పించబడింది",
  "raise.success.desc": "ఫిర్యాదు ట్రాక్ చేయడానికి ఈ ID సేవ్ చేయండి:",
  "raise.success.track": "ఫిర్యాదు ట్రాక్ చేయండి",

  // Notices
  "notices.title": "నోటీసులు మరియు ప్రకటనలు",
  "notices.hero.desc": "మునిసిపాలిటీ నుండి అధికారిక నోటీసులు మరియు నవీకరణలు.",
  "notices.empty": "ప్రస్తుతం నోటీసులు లేవు.",
  "notices.error": "నోటీసులు లోడ్ చేయడం విఫలమైంది.",
  "notices.viewpdf": "PDF చూడండి",

  // Transparency
  "transparency.title": "పారదర్శకత డాష్‌బోర్డ్",
  "transparency.hero.desc": "ప్రాంతం వారీగా మరియు విభాగ పనితీరు. పబ్లిక్ వ్యూ — లాగిన్ అవసరం లేదు.",
  "transparency.stat.total": "మొత్తం ఫిర్యాదులు",
  "transparency.stat.completed": "పూర్తయింది",
  "transparency.stat.pending": "పెండింగ్",
  "transparency.stat.rate": "పరిష్కార రేటు",
  "transparency.chart.title": "వర్గం (ప్రాంతం) వారీగా ఫిర్యాదులు",
  "transparency.chart.desc": "పారదర్శకత కోసం పంపిణీ",
  "transparency.chart.empty": "ఇంకా డేటా లేదు",
  "transparency.recent.title": "ఇటీవలి కార్యకలాపం",
  "transparency.recent.desc": "తాజా ఫిర్యాదు నవీకరణలు",
  "transparency.recent.empty": "ఇంకా ఫిర్యాదులు లేవు.",

  // Footer
  "footer.brand.desc": "స్మార్ట్ మునిసిపల్ ఫిర్యాదు మరియు సమావేశ నియంత్రణ — మీ సమాజంలో పారదర్శకత మరియు సమర్థవంతమైన పౌర సేవలు.",
  "footer.quicklinks": "త్వరిత లింకులు",
  "footer.contact": "మమ్మల్ని సంప్రదించండి",
  "footer.hours.title": "కార్యాలయ సమయాలు",
  "footer.hours.weekday": "సోమ – శని: ఉదయం 10:00 – సాయంత్రం 5:00",
  "footer.hours.weekend": "ఆదివారం మరియు సెలవులు: మూసివేయబడింది",
  "footer.holidays": "సెలవు క్యాలెండర్",
  "footer.holiday.note": "రాష్ట్ర ప్రభుత్వ ఆదేశాల ప్రకారం సెలవులు.",
  "footer.holiday.public": "పబ్లిక్ సెలవు",
  "footer.holiday.weekly": "వారపు సెలవు",
  "footer.holiday.list": "సెలవు జాబితా",
  "footer.rights": "అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.",
  "footer.noauth": "ఫిర్యాదు ట్రాకింగ్ మరియు సమర్పణకు లాగిన్ అవసరం లేదు.",
  "footer.link.home": "హోమ్",
  "footer.link.track": "ఫిర్యాదు ట్రాక్ చేయండి",
  "footer.link.raise": "ఫిర్యాదు నమోదు చేయండి",
  "footer.link.transparency": "పారదర్శకత పోర్టల్",
  "footer.link.meetings": "పబ్లిక్ సమావేశాలు",
  "footer.link.notices": "నోటీసులు",

  // Dashboard
  "dash.dashboard": "డాష్‌బోర్డ్",
  "dash.complaints": "ఫిర్యాదులు",
  "dash.meetings": "సమావేశాలు",
  "dash.tasks": "పనులు",
  "dash.bills": "బిల్లులు",
  "dash.payments": "చెల్లింపులు",
  "dash.departments": "విభాగాలు",
  "dash.staff": "సిబ్బంది",
  "dash.notifications": "నోటీసులు",
  "dash.reports": "నివేదికలు",
  "dash.audit": "ఆడిట్",
  "dash.projects": "ప్రాజెక్టులు",
  "dash.notices": "నోటీసు నిర్వహణ",
  "dash.profile": "ప్రొఫైల్",
  "dash.logout": "లాగ్ అవుట్",
  "dash.search": "ఫిర్యాదులు, పనులు, సమావేశాలు వెతకండి...",
  "dash.notifications.label": "నోటీసులు",
  "dash.switchrole": "పాత్ర మార్చండి (డెమో)",
  "dash.myprofile": "నా ప్రొఫైల్",
};

const bn: Record<string, string> = {
  ...en,
  "lang.select": "ভাষা নির্বাচন করুন",

  // Nav
  "nav.home": "হোম",
  "nav.track": "অভিযোগ ট্র্যাক করুন",
  "nav.raise": "অভিযোগ জানান",
  "nav.transparency": "স্বচ্ছতা",
  "nav.notices": "নোটিস",
  "nav.login": "স্টাফ লগইন",
  "nav.meetings": "মিটিংস",

  // Hero
  "hero.badge": "সরকারি স্বচ্ছতা পোর্টাল",
  "hero.title1": "স্মার্ট মিউনিসিপাল",
  "hero.title2": "অভিযোগ ও নিয়ন্ত্রণ",
  "hero.subtitle": "অভিযোগ ট্র্যাক করুন, মিটিং দেখুন, এবং সম্পূর্ণ স্বচ্ছতার সাথে সমস্যা জানান। লগইন প্রয়োজন নেই।",
  "hero.track": "অভিযোগ ট্র্যাক করুন",
  "hero.raise": "অভিযোগ জানান",
  "hero.transparency": "স্বচ্ছতা",

  // Stats
  "stats.heading": "লাইভ স্বচ্ছতা পরিসংখ্যান",
  "stats.total": "মোট অভিযোগ",
  "stats.completed": "সম্পন্ন কাজ",
  "stats.pending": "মুলতুবি সমস্যা",
  "stats.score": "স্বচ্ছতা স্কোর",

  // Features
  "features.heading": "নাগরিক সেবা",
  "features.subheading": "আপনি কী করতে পারেন",
  "features.desc": "লগইন প্রয়োজন নেই। যেকোনো সময় ট্র্যাক করুন, জমা দিন, বা পাবলিক তথ্য দেখুন।",
  "features.track.title": "ID দিয়ে ট্র্যাক করুন",
  "features.track.desc": "অভিযোগ ID দিয়ে খুঁজুন এবং স্ট্যাটাস দেখুন: মুলতুবি, প্রক্রিয়াধীন, মিটিং নির্ধারিত, বা সম্পন্ন।",
  "features.track.cta": "অভিযোগ ট্র্যাক করুন",
  "features.raise.title": "অভিযোগ জানান",
  "features.raise.desc": "OTP যাচাইয়ের মাধ্যমে জমা দিন। শিরোনাম, বিবরণ, অবস্থান এবং ছবি যোগ করুন — অ্যাকাউন্ট প্রয়োজন নেই।",
  "features.raise.cta": "অভিযোগ জানান",
  "features.meetings.title": "পাবলিক মিটিং",
  "features.meetings.desc": "মিটিং সারসংক্ষেপ, কাজের অগ্রগতি, এবং অনুমোদনের স্ট্যাটাস রিড-অনলি স্বচ্ছতা মোডে দেখুন।",
  "features.meetings.cta": "মিটিং দেখুন",

  // Track page
  "track.title": "অভিযোগ ট্র্যাক করুন",
  "track.hero.desc": "বর্তমান স্ট্যাটাস দেখতে অভিযোগ ID লিখুন: মুলতুবি, প্রক্রিয়াধীন, মিটিং নির্ধারিত, বা সম্পন্ন।",
  "track.card.title": "অভিযোগ ID দিয়ে খুঁজুন",
  "track.card.desc": "অভিযোগ জমা দেওয়ার সময় পাওয়া ID ব্যবহার করুন।",
  "track.placeholder": "যেমন C-1245 বা অভিযোগ ID",
  "track.button": "ট্র্যাক করুন",
  "track.process": "অভিযোগ প্রক্রিয়া",
  "track.location": "অবস্থান",
  "track.category": "বিভাগ",
  "track.submitted": "জমা দেওয়া হয়েছে",
  "track.updated": "আপডেট হয়েছে",
  "track.step.pending": "মুলতুবি",
  "track.step.assigned": "নিযুক্ত",
  "track.step.inprogress": "প্রক্রিয়াধীন",
  "track.step.meeting": "মিটিং নির্ধারিত",
  "track.step.completed": "সম্পন্ন",
  "track.step.rejected": "প্রত্যাখ্যাত",

  // Raise complaint
  "raise.title": "অভিযোগ জানান (লগইন ছাড়া)",
  "raise.hero.desc": "OTP যাচাই করুন, তারপর শিরোনাম, বিবরণ, অবস্থান এবং ঐচ্ছিক ছবি জমা দিন।",
  "raise.step1.title": "ধাপ ১: যোগাযোগ",
  "raise.step1.desc": "OTP পেতে ফোন বা ইমেইল লিখুন",
  "raise.step2.title": "ধাপ ২: OTP যাচাই করুন",
  "raise.step2.desc": "আপনাকে পাঠানো ৬-সংখ্যার কোড লিখুন",
  "raise.step3.title": "ধাপ ৩: অভিযোগের বিবরণ",
  "raise.step3.desc": "অভিযোগের বিবরণ পূরণ করুন",
  "raise.label.contact": "ফোন বা ইমেইল",
  "raise.placeholder.contact": "যেমন 9876543210 বা email@example.com",
  "raise.btn.sendotp": "OTP পাঠান",
  "raise.label.otp": "OTP",
  "raise.placeholder.otp": "৬-সংখ্যার কোড",
  "raise.btn.verify": "যাচাই করুন",
  "raise.btn.change": "নম্বর/ইমেইল পরিবর্তন করুন",
  "raise.label.title": "শিরোনাম *",
  "raise.placeholder.title": "সংক্ষিপ্ত শিরোনাম",
  "raise.label.desc": "বিবরণ *",
  "raise.placeholder.desc": "সমস্যা বর্ণনা করুন",
  "raise.label.location": "অবস্থান (ঠিকানা বা এলাকা)",
  "raise.placeholder.location": "যেমন ব্লক A, মেইন রোড",
  "raise.label.category": "বিভাগ",
  "raise.label.priority": "অগ্রাধিকার",
  "raise.label.images": "ছবি (ঐচ্ছিক, সর্বোচ্চ ৫)",
  "raise.btn.addimage": "ছবি যোগ করুন",
  "raise.btn.submit": "অভিযোগ জমা দিন",
  "raise.success.title": "অভিযোগ জমা হয়েছে",
  "raise.success.desc": "অভিযোগ ট্র্যাক করতে এই ID সংরক্ষণ করুন:",
  "raise.success.track": "অভিযোগ ট্র্যাক করুন",

  // Notices
  "notices.title": "নোটিস ও ঘোষণা",
  "notices.hero.desc": "পৌরসভার পক্ষ থেকে সরকারি নোটিস ও আপডেট।",
  "notices.empty": "এখন কোনো নোটিস নেই।",
  "notices.error": "নোটিস লোড করতে ব্যর্থ।",
  "notices.viewpdf": "PDF দেখুন",

  // Transparency
  "transparency.title": "স্বচ্ছতা ড্যাশবোর্ড",
  "transparency.hero.desc": "এলাকাভিত্তিক ও বিভাগীয় কর্মক্ষমতা। পাবলিক ভিউ — লগইন প্রয়োজন নেই।",
  "transparency.stat.total": "মোট অভিযোগ",
  "transparency.stat.completed": "সম্পন্ন",
  "transparency.stat.pending": "মুলতুবি",
  "transparency.stat.rate": "সমাধানের হার",
  "transparency.chart.title": "বিভাগ (এলাকা) অনুযায়ী অভিযোগ",
  "transparency.chart.desc": "স্বচ্ছতার জন্য বিতরণ",
  "transparency.chart.empty": "এখনো ডেটা নেই",
  "transparency.recent.title": "সাম্প্রতিক কার্যক্রম",
  "transparency.recent.desc": "সর্বশেষ অভিযোগ আপডেট",
  "transparency.recent.empty": "এখনো কোনো অভিযোগ নেই।",

  // Footer
  "footer.brand.desc": "স্মার্ট মিউনিসিপাল অভিযোগ ও মিটিং নিয়ন্ত্রণ — আপনার সম্প্রদায়ে স্বচ্ছতা ও দক্ষ নাগরিক সেবা।",
  "footer.quicklinks": "দ্রুত লিংক",
  "footer.contact": "আমাদের সাথে যোগাযোগ করুন",
  "footer.hours.title": "অফিস সময়",
  "footer.hours.weekday": "সোম – শনি: সকাল ১০:০০ – বিকাল ৫:০০",
  "footer.hours.weekend": "রবিবার ও ছুটির দিন: বন্ধ",
  "footer.holidays": "ছুটির ক্যালেন্ডার",
  "footer.holiday.note": "রাজ্য সরকারের আদেশ অনুযায়ী ছুটি।",
  "footer.holiday.public": "সরকারি ছুটি",
  "footer.holiday.weekly": "সাপ্তাহিক ছুটি",
  "footer.holiday.list": "ছুটির তালিকা",
  "footer.rights": "সর্বস্বত্ব সংরক্ষিত।",
  "footer.noauth": "অভিযোগ ট্র্যাকিং ও জমা দেওয়ার জন্য লগইন প্রয়োজন নেই।",
  "footer.link.home": "হোম",
  "footer.link.track": "অভিযোগ ট্র্যাক করুন",
  "footer.link.raise": "অভিযোগ জানান",
  "footer.link.transparency": "স্বচ্ছতা পোর্টাল",
  "footer.link.meetings": "পাবলিক মিটিং",
  "footer.link.notices": "নোটিস",

  // Dashboard
  "dash.dashboard": "ড্যাশবোর্ড",
  "dash.complaints": "অভিযোগ",
  "dash.meetings": "মিটিংস",
  "dash.tasks": "কাজ",
  "dash.bills": "বিল",
  "dash.payments": "পেমেন্ট",
  "dash.departments": "বিভাগ",
  "dash.staff": "স্টাফ",
  "dash.notifications": "নোটিস",
  "dash.reports": "রিপোর্ট",
  "dash.audit": "অডিট",
  "dash.projects": "প্রকল্প",
  "dash.notices": "নোটিস ব্যবস্থাপনা",
  "dash.profile": "প্রোফাইল",
  "dash.logout": "লগ আউট",
  "dash.search": "অভিযোগ, কাজ, মিটিং খুঁজুন...",
  "dash.notifications.label": "নোটিস",
  "dash.switchrole": "ভূমিকা পরিবর্তন করুন (ডেমো)",
  "dash.myprofile": "আমার প্রোফাইল",
};

const pa: Record<string, string> = {
  ...en,
  "lang.select": "ਭਾਸ਼ਾ ਚੁਣੋ",

  // Nav
  "nav.home": "ਹੋਮ",
  "nav.track": "ਸ਼ਿਕਾਇਤ ਟ੍ਰੈਕ ਕਰੋ",
  "nav.raise": "ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ",
  "nav.transparency": "ਪਾਰਦਰਸ਼ਤਾ",
  "nav.notices": "ਨੋਟਿਸ",
  "nav.login": "ਸਟਾਫ ਲੌਗਇਨ",
  "nav.meetings": "ਮੀਟਿੰਗਾਂ",

  // Hero
  "hero.badge": "ਸਰਕਾਰੀ ਪਾਰਦਰਸ਼ਤਾ ਪੋਰਟਲ",
  "hero.title1": "ਸਮਾਰਟ ਮਿਉਂਸੀਪਲ",
  "hero.title2": "ਸ਼ਿਕਾਇਤ ਅਤੇ ਨਿਯੰਤਰਣ",
  "hero.subtitle": "ਸ਼ਿਕਾਇਤਾਂ ਟ੍ਰੈਕ ਕਰੋ, ਮੀਟਿੰਗਾਂ ਦੇਖੋ, ਅਤੇ ਪੂਰੀ ਪਾਰਦਰਸ਼ਤਾ ਨਾਲ ਸਮੱਸਿਆਵਾਂ ਦਰਜ ਕਰੋ। ਲੌਗਇਨ ਦੀ ਲੋੜ ਨਹੀਂ।",
  "hero.track": "ਸ਼ਿਕਾਇਤ ਟ੍ਰੈਕ ਕਰੋ",
  "hero.raise": "ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ",
  "hero.transparency": "ਪਾਰਦਰਸ਼ਤਾ",

  // Stats
  "stats.heading": "ਲਾਈਵ ਪਾਰਦਰਸ਼ਤਾ ਅੰਕੜੇ",
  "stats.total": "ਕੁੱਲ ਸ਼ਿਕਾਇਤਾਂ",
  "stats.completed": "ਪੂਰੇ ਕੀਤੇ ਕੰਮ",
  "stats.pending": "ਬਕਾਇਆ ਸਮੱਸਿਆਵਾਂ",
  "stats.score": "ਪਾਰਦਰਸ਼ਤਾ ਸਕੋਰ",

  // Features
  "features.heading": "ਨਾਗਰਿਕ ਸੇਵਾਵਾਂ",
  "features.subheading": "ਤੁਸੀਂ ਕੀ ਕਰ ਸਕਦੇ ਹੋ",
  "features.desc": "ਲੌਗਇਨ ਦੀ ਲੋੜ ਨਹੀਂ। ਕਦੇ ਵੀ ਟ੍ਰੈਕ ਕਰੋ, ਜਮ੍ਹਾਂ ਕਰੋ, ਜਾਂ ਜਨਤਕ ਜਾਣਕਾਰੀ ਦੇਖੋ।",
  "features.track.title": "ID ਨਾਲ ਟ੍ਰੈਕ ਕਰੋ",
  "features.track.desc": "ਸ਼ਿਕਾਇਤ ID ਨਾਲ ਖੋਜੋ ਅਤੇ ਸਥਿਤੀ ਦੇਖੋ: ਬਕਾਇਆ, ਪ੍ਰਕਿਰਿਆ ਵਿੱਚ, ਮੀਟਿੰਗ ਨਿਰਧਾਰਿਤ, ਜਾਂ ਪੂਰੀ।",
  "features.track.cta": "ਸ਼ਿਕਾਇਤ ਟ੍ਰੈਕ ਕਰੋ",
  "features.raise.title": "ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ",
  "features.raise.desc": "OTP ਤਸਦੀਕ ਨਾਲ ਜਮ੍ਹਾਂ ਕਰੋ। ਸਿਰਲੇਖ, ਵੇਰਵਾ, ਸਥਾਨ ਅਤੇ ਫੋਟੋਆਂ ਜੋੜੋ — ਖਾਤਾ ਜ਼ਰੂਰੀ ਨਹੀਂ।",
  "features.raise.cta": "ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ",
  "features.meetings.title": "ਜਨਤਕ ਮੀਟਿੰਗਾਂ",
  "features.meetings.desc": "ਮੀਟਿੰਗ ਸਾਰਾਂਸ਼, ਕੰਮ ਦੀ ਪ੍ਰਗਤੀ, ਅਤੇ ਮਨਜ਼ੂਰੀ ਸਥਿਤੀ ਰੀਡ-ਓਨਲੀ ਪਾਰਦਰਸ਼ਤਾ ਮੋਡ ਵਿੱਚ ਦੇਖੋ।",
  "features.meetings.cta": "ਮੀਟਿੰਗਾਂ ਦੇਖੋ",

  // Track page
  "track.title": "ਸ਼ਿਕਾਇਤ ਟ੍ਰੈਕ ਕਰੋ",
  "track.hero.desc": "ਮੌਜੂਦਾ ਸਥਿਤੀ ਦੇਖਣ ਲਈ ਸ਼ਿਕਾਇਤ ID ਦਰਜ ਕਰੋ: ਬਕਾਇਆ, ਪ੍ਰਕਿਰਿਆ ਵਿੱਚ, ਮੀਟਿੰਗ ਨਿਰਧਾਰਿਤ, ਜਾਂ ਪੂਰੀ।",
  "track.card.title": "ਸ਼ਿਕਾਇਤ ID ਨਾਲ ਖੋਜੋ",
  "track.card.desc": "ਸ਼ਿਕਾਇਤ ਜਮ੍ਹਾਂ ਕਰਨ ਵੇਲੇ ਮਿਲੀ ID ਵਰਤੋ।",
  "track.placeholder": "ਜਿਵੇਂ C-1245 ਜਾਂ ਸ਼ਿਕਾਇਤ ID",
  "track.button": "ਟ੍ਰੈਕ ਕਰੋ",
  "track.process": "ਸ਼ਿਕਾਇਤ ਪ੍ਰਕਿਰਿਆ",
  "track.location": "ਸਥਾਨ",
  "track.category": "ਸ਼੍ਰੇਣੀ",
  "track.submitted": "ਜਮ੍ਹਾਂ ਕੀਤਾ",
  "track.updated": "ਅੱਪਡੇਟ ਕੀਤਾ",
  "track.step.pending": "ਬਕਾਇਆ",
  "track.step.assigned": "ਸੌਂਪਿਆ ਗਿਆ",
  "track.step.inprogress": "ਪ੍ਰਕਿਰਿਆ ਵਿੱਚ",
  "track.step.meeting": "ਮੀਟਿੰਗ ਨਿਰਧਾਰਿਤ",
  "track.step.completed": "ਪੂਰੀ",
  "track.step.rejected": "ਰੱਦ ਕੀਤਾ",

  // Raise complaint
  "raise.title": "ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ (ਲੌਗਇਨ ਤੋਂ ਬਿਨਾਂ)",
  "raise.hero.desc": "OTP ਤਸਦੀਕ ਕਰੋ, ਫਿਰ ਸਿਰਲੇਖ, ਵੇਰਵਾ, ਸਥਾਨ ਅਤੇ ਵਿਕਲਪਿਕ ਫੋਟੋਆਂ ਜਮ੍ਹਾਂ ਕਰੋ।",
  "raise.step1.title": "ਕਦਮ 1: ਸੰਪਰਕ",
  "raise.step1.desc": "OTP ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਫੋਨ ਜਾਂ ਈਮੇਲ ਦਰਜ ਕਰੋ",
  "raise.step2.title": "ਕਦਮ 2: OTP ਤਸਦੀਕ ਕਰੋ",
  "raise.step2.desc": "ਤੁਹਾਨੂੰ ਭੇਜਿਆ 6-ਅੰਕੀ ਕੋਡ ਦਰਜ ਕਰੋ",
  "raise.step3.title": "ਕਦਮ 3: ਸ਼ਿਕਾਇਤ ਵੇਰਵੇ",
  "raise.step3.desc": "ਸ਼ਿਕਾਇਤ ਦੇ ਵੇਰਵੇ ਭਰੋ",
  "raise.label.contact": "ਫੋਨ ਜਾਂ ਈਮੇਲ",
  "raise.placeholder.contact": "ਜਿਵੇਂ 9876543210 ਜਾਂ email@example.com",
  "raise.btn.sendotp": "OTP ਭੇਜੋ",
  "raise.label.otp": "OTP",
  "raise.placeholder.otp": "6-ਅੰਕੀ ਕੋਡ",
  "raise.btn.verify": "ਤਸਦੀਕ ਕਰੋ",
  "raise.btn.change": "ਨੰਬਰ/ਈਮੇਲ ਬਦਲੋ",
  "raise.label.title": "ਸਿਰਲੇਖ *",
  "raise.placeholder.title": "ਸੰਖੇਪ ਸਿਰਲੇਖ",
  "raise.label.desc": "ਵੇਰਵਾ *",
  "raise.placeholder.desc": "ਸਮੱਸਿਆ ਦੱਸੋ",
  "raise.label.location": "ਸਥਾਨ (ਪਤਾ ਜਾਂ ਖੇਤਰ)",
  "raise.placeholder.location": "ਜਿਵੇਂ ਬਲਾਕ A, ਮੁੱਖ ਸੜਕ",
  "raise.label.category": "ਸ਼੍ਰੇਣੀ",
  "raise.label.priority": "ਤਰਜੀਹ",
  "raise.label.images": "ਫੋਟੋਆਂ (ਵਿਕਲਪਿਕ, ਵੱਧ ਤੋਂ ਵੱਧ 5)",
  "raise.btn.addimage": "ਫੋਟੋ ਜੋੜੋ",
  "raise.btn.submit": "ਸ਼ਿਕਾਇਤ ਜਮ੍ਹਾਂ ਕਰੋ",
  "raise.success.title": "ਸ਼ਿਕਾਇਤ ਜਮ੍ਹਾਂ ਹੋਈ",
  "raise.success.desc": "ਸ਼ਿਕਾਇਤ ਟ੍ਰੈਕ ਕਰਨ ਲਈ ਇਹ ID ਸੰਭਾਲੋ:",
  "raise.success.track": "ਸ਼ਿਕਾਇਤ ਟ੍ਰੈਕ ਕਰੋ",

  // Notices
  "notices.title": "ਨੋਟਿਸ ਅਤੇ ਐਲਾਨ",
  "notices.hero.desc": "ਨਗਰਪਾਲਿਕਾ ਵੱਲੋਂ ਅਧਿਕਾਰਤ ਨੋਟਿਸ ਅਤੇ ਅੱਪਡੇਟ।",
  "notices.empty": "ਹੁਣ ਕੋਈ ਨੋਟਿਸ ਨਹੀਂ।",
  "notices.error": "ਨੋਟਿਸ ਲੋਡ ਕਰਨ ਵਿੱਚ ਅਸਫਲ।",
  "notices.viewpdf": "PDF ਦੇਖੋ",

  // Transparency
  "transparency.title": "ਪਾਰਦਰਸ਼ਤਾ ਡੈਸ਼ਬੋਰਡ",
  "transparency.hero.desc": "ਖੇਤਰ-ਵਾਰ ਅਤੇ ਵਿਭਾਗ ਪ੍ਰਦਰਸ਼ਨ। ਜਨਤਕ ਦ੍ਰਿਸ਼ — ਲੌਗਇਨ ਦੀ ਲੋੜ ਨਹੀਂ।",
  "transparency.stat.total": "ਕੁੱਲ ਸ਼ਿਕਾਇਤਾਂ",
  "transparency.stat.completed": "ਪੂਰੀਆਂ",
  "transparency.stat.pending": "ਬਕਾਇਆ",
  "transparency.stat.rate": "ਹੱਲ ਦਰ",
  "transparency.chart.title": "ਸ਼੍ਰੇਣੀ (ਖੇਤਰ) ਅਨੁਸਾਰ ਸ਼ਿਕਾਇਤਾਂ",
  "transparency.chart.desc": "ਪਾਰਦਰਸ਼ਤਾ ਲਈ ਵੰਡ",
  "transparency.chart.empty": "ਅਜੇ ਡੇਟਾ ਨਹੀਂ",
  "transparency.recent.title": "ਤਾਜ਼ਾ ਗਤੀਵਿਧੀ",
  "transparency.recent.desc": "ਨਵੀਨਤਮ ਸ਼ਿਕਾਇਤ ਅੱਪਡੇਟ",
  "transparency.recent.empty": "ਅਜੇ ਕੋਈ ਸ਼ਿਕਾਇਤ ਨਹੀਂ।",

  // Footer
  "footer.brand.desc": "ਸਮਾਰਟ ਮਿਉਂਸੀਪਲ ਸ਼ਿਕਾਇਤ ਅਤੇ ਮੀਟਿੰਗ ਨਿਯੰਤਰਣ — ਤੁਹਾਡੇ ਭਾਈਚਾਰੇ ਵਿੱਚ ਪਾਰਦਰਸ਼ਤਾ ਅਤੇ ਕੁਸ਼ਲ ਨਾਗਰਿਕ ਸੇਵਾਵਾਂ।",
  "footer.quicklinks": "ਤੇਜ਼ ਲਿੰਕ",
  "footer.contact": "ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
  "footer.hours.title": "ਦਫ਼ਤਰ ਸਮਾਂ",
  "footer.hours.weekday": "ਸੋਮ – ਸ਼ਨੀ: ਸਵੇਰੇ 10:00 – ਸ਼ਾਮ 5:00",
  "footer.hours.weekend": "ਐਤਵਾਰ ਅਤੇ ਛੁੱਟੀਆਂ: ਬੰਦ",
  "footer.holidays": "ਛੁੱਟੀ ਕੈਲੰਡਰ",
  "footer.holiday.note": "ਰਾਜ ਸਰਕਾਰ ਦੇ ਹੁਕਮਾਂ ਅਨੁਸਾਰ ਛੁੱਟੀਆਂ।",
  "footer.holiday.public": "ਜਨਤਕ ਛੁੱਟੀ",
  "footer.holiday.weekly": "ਹਫ਼ਤਾਵਾਰੀ ਛੁੱਟੀ",
  "footer.holiday.list": "ਛੁੱਟੀ ਸੂਚੀ",
  "footer.rights": "ਸਾਰੇ ਅਧਿਕਾਰ ਸੁਰੱਖਿਅਤ।",
  "footer.noauth": "ਸ਼ਿਕਾਇਤ ਟ੍ਰੈਕਿੰਗ ਅਤੇ ਜਮ੍ਹਾਂ ਕਰਨ ਲਈ ਲੌਗਇਨ ਦੀ ਲੋੜ ਨਹੀਂ।",
  "footer.link.home": "ਹੋਮ",
  "footer.link.track": "ਸ਼ਿਕਾਇਤ ਟ੍ਰੈਕ ਕਰੋ",
  "footer.link.raise": "ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ",
  "footer.link.transparency": "ਪਾਰਦਰਸ਼ਤਾ ਪੋਰਟਲ",
  "footer.link.meetings": "ਜਨਤਕ ਮੀਟਿੰਗਾਂ",
  "footer.link.notices": "ਨੋਟਿਸ",

  // Dashboard
  "dash.dashboard": "ਡੈਸ਼ਬੋਰਡ",
  "dash.complaints": "ਸ਼ਿਕਾਇਤਾਂ",
  "dash.meetings": "ਮੀਟਿੰਗਾਂ",
  "dash.tasks": "ਕੰਮ",
  "dash.bills": "ਬਿੱਲ",
  "dash.payments": "ਭੁਗਤਾਨ",
  "dash.departments": "ਵਿਭਾਗ",
  "dash.staff": "ਸਟਾਫ",
  "dash.notifications": "ਨੋਟਿਸ",
  "dash.reports": "ਰਿਪੋਰਟਾਂ",
  "dash.audit": "ਆਡਿਟ",
  "dash.projects": "ਪ੍ਰੋਜੈਕਟ",
  "dash.notices": "ਨੋਟਿਸ ਪ੍ਰਬੰਧਨ",
  "dash.profile": "ਪ੍ਰੋਫਾਈਲ",
  "dash.logout": "ਲੌਗ ਆਉਟ",
  "dash.search": "ਸ਼ਿਕਾਇਤਾਂ, ਕੰਮ, ਮੀਟਿੰਗਾਂ ਖੋਜੋ...",
  "dash.notifications.label": "ਨੋਟਿਸ",
  "dash.switchrole": "ਭੂਮਿਕਾ ਬਦਲੋ (ਡੈਮੋ)",
  "dash.myprofile": "ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ",
};

const kn: Record<string, string> = {
  ...en,
  "lang.select": "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",

  // Nav
  "nav.home": "ಮುಖಪುಟ",
  "nav.track": "ದೂರು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
  "nav.raise": "ದೂರು ದಾಖಲಿಸಿ",
  "nav.transparency": "ಪಾರದರ್ಶಕತೆ",
  "nav.notices": "ಸೂಚನೆಗಳು",
  "nav.login": "ಸಿಬ್ಬಂದಿ ಲಾಗಿನ್",
  "nav.meetings": "ಸಭೆಗಳು",

  // Hero
  "hero.badge": "ಸರ್ಕಾರಿ ಪಾರದರ್ಶಕತೆ ಪೋರ್ಟಲ್",
  "hero.title1": "ಸ್ಮಾರ್ಟ್ ಮುನಿಸಿಪಲ್",
  "hero.title2": "ದೂರು ಮತ್ತು ನಿಯಂತ್ರಣ",
  "hero.subtitle": "ದೂರುಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ, ಸಭೆಗಳನ್ನು ನೋಡಿ, ಮತ್ತು ಸಂಪೂರ್ಣ ಪಾರದರ್ಶಕತೆಯೊಂದಿಗೆ ಸಮಸ್ಯೆಗಳನ್ನು ದಾಖಲಿಸಿ. ಲಾಗಿನ್ ಅಗತ್ಯವಿಲ್ಲ.",
  "hero.track": "ದೂರು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
  "hero.raise": "ದೂರು ದಾಖಲಿಸಿ",
  "hero.transparency": "ಪಾರದರ್ಶಕತೆ",

  // Stats
  "stats.heading": "ಲೈವ್ ಪಾರದರ್ಶಕತೆ ಅಂಕಿಅಂಶಗಳು",
  "stats.total": "ಒಟ್ಟು ದೂರುಗಳು",
  "stats.completed": "ಪೂರ್ಣಗೊಂಡ ಕಾರ್ಯಗಳು",
  "stats.pending": "ಬಾಕಿ ಸಮಸ್ಯೆಗಳು",
  "stats.score": "ಪಾರದರ್ಶಕತೆ ಸ್ಕೋರ್",

  // Features
  "features.heading": "ನಾಗರಿಕ ಸೇವೆಗಳು",
  "features.subheading": "ನೀವು ಏನು ಮಾಡಬಹುದು",
  "features.desc": "ಲಾಗಿನ್ ಅಗತ್ಯವಿಲ್ಲ. ಯಾವಾಗಲಾದರೂ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ, ಸಲ್ಲಿಸಿ, ಅಥವಾ ಸಾರ್ವಜನಿಕ ಮಾಹಿತಿ ನೋಡಿ.",
  "features.track.title": "ID ಮೂಲಕ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
  "features.track.desc": "ದೂರು ID ಮೂಲಕ ಹುಡುಕಿ ಮತ್ತು ಸ್ಥಿತಿ ನೋಡಿ: ಬಾಕಿ, ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿ, ಸಭೆ ನಿಗದಿಪಡಿಸಲಾಗಿದೆ, ಅಥವಾ ಪೂರ್ಣ.",
  "features.track.cta": "ದೂರು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
  "features.raise.title": "ದೂರು ದಾಖಲಿಸಿ",
  "features.raise.desc": "OTP ಪರಿಶೀಲನೆಯೊಂದಿಗೆ ಸಲ್ಲಿಸಿ. ಶೀರ್ಷಿಕೆ, ವಿವರಣೆ, ಸ್ಥಳ ಮತ್ತು ಚಿತ್ರಗಳನ್ನು ಸೇರಿಸಿ — ಖಾತೆ ಅಗತ್ಯವಿಲ್ಲ.",
  "features.raise.cta": "ದೂರು ದಾಖಲಿಸಿ",
  "features.meetings.title": "ಸಾರ್ವಜನಿಕ ಸಭೆಗಳು",
  "features.meetings.desc": "ಸಭೆ ಸಾರಾಂಶಗಳು, ಕಾರ್ಯ ಪ್ರಗತಿ, ಮತ್ತು ಅನುಮೋದನೆ ಸ್ಥಿತಿಯನ್ನು ರೀಡ್-ಓನ್ಲಿ ಪಾರದರ್ಶಕತೆ ಮೋಡ್‌ನಲ್ಲಿ ನೋಡಿ.",
  "features.meetings.cta": "ಸಭೆಗಳನ್ನು ನೋಡಿ",

  // Track page
  "track.title": "ದೂರು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
  "track.hero.desc": "ಪ್ರಸ್ತುತ ಸ್ಥಿತಿ ನೋಡಲು ದೂರು ID ನಮೂದಿಸಿ: ಬಾಕಿ, ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿ, ಸಭೆ ನಿಗದಿಪಡಿಸಲಾಗಿದೆ, ಅಥವಾ ಪೂರ್ಣ.",
  "track.card.title": "ದೂರು ID ಮೂಲಕ ಹುಡುಕಿ",
  "track.card.desc": "ದೂರು ಸಲ್ಲಿಸಿದಾಗ ಸಿಕ್ಕ ID ಬಳಸಿ.",
  "track.placeholder": "ಉದಾ. C-1245 ಅಥವಾ ದೂರು ID",
  "track.button": "ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
  "track.process": "ದೂರು ಪ್ರಕ್ರಿಯೆ",
  "track.location": "ಸ್ಥಳ",
  "track.category": "ವರ್ಗ",
  "track.submitted": "ಸಲ್ಲಿಸಲಾಗಿದೆ",
  "track.updated": "ನವೀಕರಿಸಲಾಗಿದೆ",
  "track.step.pending": "ಬಾಕಿ",
  "track.step.assigned": "ನಿಯೋಜಿಸಲಾಗಿದೆ",
  "track.step.inprogress": "ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿ",
  "track.step.meeting": "ಸಭೆ ನಿಗದಿಪಡಿಸಲಾಗಿದೆ",
  "track.step.completed": "ಪೂರ್ಣ",
  "track.step.rejected": "ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",

  // Raise complaint
  "raise.title": "ದೂರು ದಾಖಲಿಸಿ (ಲಾಗಿನ್ ಇಲ್ಲದೆ)",
  "raise.hero.desc": "OTP ಪರಿಶೀಲಿಸಿ, ನಂತರ ಶೀರ್ಷಿಕೆ, ವಿವರಣೆ, ಸ್ಥಳ ಮತ್ತು ಐಚ್ಛಿಕ ಚಿತ್ರಗಳನ್ನು ಸಲ್ಲಿಸಿ.",
  "raise.step1.title": "ಹಂತ 1: ಸಂಪರ್ಕ",
  "raise.step1.desc": "OTP ಪಡೆಯಲು ಫೋನ್ ಅಥವಾ ಇಮೇಲ್ ನಮೂದಿಸಿ",
  "raise.step2.title": "ಹಂತ 2: OTP ಪರಿಶೀಲಿಸಿ",
  "raise.step2.desc": "ನಿಮಗೆ ಕಳುಹಿಸಿದ 6-ಅಂಕಿ ಕೋಡ್ ನಮೂದಿಸಿ",
  "raise.step3.title": "ಹಂತ 3: ದೂರು ವಿವರಗಳು",
  "raise.step3.desc": "ದೂರಿನ ವಿವರಗಳನ್ನು ತುಂಬಿ",
  "raise.label.contact": "ಫೋನ್ ಅಥವಾ ಇಮೇಲ್",
  "raise.placeholder.contact": "ಉದಾ. 9876543210 ಅಥವಾ email@example.com",
  "raise.btn.sendotp": "OTP ಕಳುಹಿಸಿ",
  "raise.label.otp": "OTP",
  "raise.placeholder.otp": "6-ಅಂಕಿ ಕೋಡ್",
  "raise.btn.verify": "ಪರಿಶೀಲಿಸಿ",
  "raise.btn.change": "ನಂಬರ್/ಇಮೇಲ್ ಬದಲಿಸಿ",
  "raise.label.title": "ಶೀರ್ಷಿಕೆ *",
  "raise.placeholder.title": "ಸಂಕ್ಷಿಪ್ತ ಶೀರ್ಷಿಕೆ",
  "raise.label.desc": "ವಿವರಣೆ *",
  "raise.placeholder.desc": "ಸಮಸ್ಯೆ ವಿವರಿಸಿ",
  "raise.label.location": "ಸ್ಥಳ (ವಿಳಾಸ ಅಥವಾ ಪ್ರದೇಶ)",
  "raise.placeholder.location": "ಉದಾ. ಬ್ಲಾಕ್ A, ಮುಖ್ಯ ರಸ್ತೆ",
  "raise.label.category": "ವರ್ಗ",
  "raise.label.priority": "ಆದ್ಯತೆ",
  "raise.label.images": "ಚಿತ್ರಗಳು (ಐಚ್ಛಿಕ, ಗರಿಷ್ಠ 5)",
  "raise.btn.addimage": "ಚಿತ್ರ ಸೇರಿಸಿ",
  "raise.btn.submit": "ದೂರು ಸಲ್ಲಿಸಿ",
  "raise.success.title": "ದೂರು ಸಲ್ಲಿಸಲಾಗಿದೆ",
  "raise.success.desc": "ದೂರು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಈ ID ಉಳಿಸಿ:",
  "raise.success.track": "ದೂರು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",

  // Notices
  "notices.title": "ಸೂಚನೆಗಳು ಮತ್ತು ಪ್ರಕಟಣೆಗಳು",
  "notices.hero.desc": "ಪುರಸಭೆಯಿಂದ ಅಧಿಕೃತ ಸೂಚನೆಗಳು ಮತ್ತು ನವೀಕರಣಗಳು.",
  "notices.empty": "ಪ್ರಸ್ತುತ ಯಾವುದೇ ಸೂಚನೆಗಳಿಲ್ಲ.",
  "notices.error": "ಸೂಚನೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ.",
  "notices.viewpdf": "PDF ನೋಡಿ",

  // Transparency
  "transparency.title": "ಪಾರದರ್ಶಕತೆ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
  "transparency.hero.desc": "ಪ್ರದೇಶ-ವಾರು ಮತ್ತು ವಿಭಾಗ ಕಾರ್ಯಕ್ಷಮತೆ. ಸಾರ್ವಜನಿಕ ವೀಕ್ಷಣೆ — ಲಾಗಿನ್ ಅಗತ್ಯವಿಲ್ಲ.",
  "transparency.stat.total": "ಒಟ್ಟು ದೂರುಗಳು",
  "transparency.stat.completed": "ಪೂರ್ಣ",
  "transparency.stat.pending": "ಬಾಕಿ",
  "transparency.stat.rate": "ಪರಿಹಾರ ದರ",
  "transparency.chart.title": "ವರ್ಗ (ಪ್ರದೇಶ) ಪ್ರಕಾರ ದೂರುಗಳು",
  "transparency.chart.desc": "ಪಾರದರ್ಶಕತೆಗಾಗಿ ವಿತರಣೆ",
  "transparency.chart.empty": "ಇನ್ನೂ ಡೇಟಾ ಇಲ್ಲ",
  "transparency.recent.title": "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
  "transparency.recent.desc": "ಇತ್ತೀಚಿನ ದೂರು ನವೀಕರಣಗಳು",
  "transparency.recent.empty": "ಇನ್ನೂ ದೂರುಗಳಿಲ್ಲ.",

  // Footer
  "footer.brand.desc": "ಸ್ಮಾರ್ಟ್ ಮುನಿಸಿಪಲ್ ದೂರು ಮತ್ತು ಸಭೆ ನಿಯಂತ್ರಣ — ನಿಮ್ಮ ಸಮುದಾಯದಲ್ಲಿ ಪಾರದರ್ಶಕತೆ ಮತ್ತು ಪರಿಣಾಮಕಾರಿ ನಾಗರಿಕ ಸೇವೆಗಳು.",
  "footer.quicklinks": "ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು",
  "footer.contact": "ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
  "footer.hours.title": "ಕಚೇರಿ ಸಮಯ",
  "footer.hours.weekday": "ಸೋಮ – ಶನಿ: ಬೆಳಿಗ್ಗೆ 10:00 – ಸಂಜೆ 5:00",
  "footer.hours.weekend": "ಭಾನುವಾರ ಮತ್ತು ರಜಾದಿನಗಳು: ಮುಚ್ಚಿರುತ್ತದೆ",
  "footer.holidays": "ರಜಾ ಕ್ಯಾಲೆಂಡರ್",
  "footer.holiday.note": "ರಾಜ್ಯ ಸರ್ಕಾರದ ಆದೇಶಗಳ ಪ್ರಕಾರ ರಜಾದಿನಗಳು.",
  "footer.holiday.public": "ಸಾರ್ವಜನಿಕ ರಜೆ",
  "footer.holiday.weekly": "ವಾರದ ರಜೆ",
  "footer.holiday.list": "ರಜಾ ಪಟ್ಟಿ",
  "footer.rights": "ಎಲ್ಲ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
  "footer.noauth": "ದೂರು ಟ್ರ್ಯಾಕಿಂಗ್ ಮತ್ತು ಸಲ್ಲಿಕೆಗೆ ಲಾಗಿನ್ ಅಗತ್ಯವಿಲ್ಲ.",
  "footer.link.home": "ಮುಖಪುಟ",
  "footer.link.track": "ದೂರು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
  "footer.link.raise": "ದೂರು ದಾಖಲಿಸಿ",
  "footer.link.transparency": "ಪಾರದರ್ಶಕತೆ ಪೋರ್ಟಲ್",
  "footer.link.meetings": "ಸಾರ್ವಜನಿಕ ಸಭೆಗಳು",
  "footer.link.notices": "ಸೂಚನೆಗಳು",

  // Dashboard
  "dash.dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
  "dash.complaints": "ದೂರುಗಳು",
  "dash.meetings": "ಸಭೆಗಳು",
  "dash.tasks": "ಕಾರ್ಯಗಳು",
  "dash.bills": "ಬಿಲ್‌ಗಳು",
  "dash.payments": "ಪಾವತಿಗಳು",
  "dash.departments": "ವಿಭಾಗಗಳು",
  "dash.staff": "ಸಿಬ್ಬಂದಿ",
  "dash.notifications": "ಸೂಚನೆಗಳು",
  "dash.reports": "ವರದಿಗಳು",
  "dash.audit": "ಆಡಿಟ್",
  "dash.projects": "ಯೋಜನೆಗಳು",
  "dash.notices": "ಸೂಚನೆ ನಿರ್ವಹಣೆ",
  "dash.profile": "ಪ್ರೊಫೈಲ್",
  "dash.logout": "ಲಾಗ್ ಔಟ್",
  "dash.search": "ದೂರುಗಳು, ಕಾರ್ಯಗಳು, ಸಭೆಗಳನ್ನು ಹುಡುಕಿ...",
  "dash.notifications.label": "ಸೂಚನೆಗಳು",
  "dash.switchrole": "ಪಾತ್ರ ಬದಲಿಸಿ (ಡೆಮೋ)",
  "dash.myprofile": "ನನ್ನ ಪ್ರೊಫೈಲ್",
};

const ml: Record<string, string> = {
  ...en,
  "lang.select": "ഭാഷ തിരഞ്ഞെടുക്കുക",

  // Nav
  "nav.home": "ഹോം",
  "nav.track": "പരാതി ട്രാക്ക് ചെയ്യുക",
  "nav.raise": "പരാതി നൽകുക",
  "nav.transparency": "പാരദർശിത്വം",
  "nav.notices": "നോട്ടീസുകൾ",
  "nav.login": "സ്റ്റാഫ് ലോഗിൻ",
  "nav.meetings": "യോഗങ്ങൾ",

  // Hero
  "hero.badge": "സർക്കാർ പാരദർശിത്വ പോർട്ടൽ",
  "hero.title1": "സ്മാർട്ട് മുനിസിപ്പൽ",
  "hero.title2": "പരാതി & നിയന്ത്രണം",
  "hero.subtitle": "പരാതികൾ ട്രാക്ക് ചെയ്യുക, യോഗങ്ങൾ കാണുക, പൂർണ്ണ പാരദർശിത്വത്തോടെ പ്രശ്നങ്ങൾ രേഖപ്പെടുത്തുക. ലോഗിൻ ആവശ്യമില്ല.",
  "hero.track": "പരാതി ട്രാക്ക് ചെയ്യുക",
  "hero.raise": "പരാതി നൽകുക",
  "hero.transparency": "പാരദർശിത്വം",

  // Stats
  "stats.heading": "തത്സമയ പാരദർശിത്വ കണക്കുകൾ",
  "stats.total": "മൊത്തം പരാതികൾ",
  "stats.completed": "പൂർത്തിയായ ജോലികൾ",
  "stats.pending": "തീർപ്പാകാത്ത പ്രശ്നങ്ങൾ",
  "stats.score": "പാരദർശിത്വ സ്കോർ",

  // Features
  "features.heading": "പൗര സേവനങ്ങൾ",
  "features.subheading": "നിങ്ങൾക്ക് എന്ത് ചെയ്യാം",
  "features.desc": "ലോഗിൻ ആവശ്യമില്ല. എപ്പോൾ വേണമെങ്കിലും ട്രാക്ക് ചെയ്യുക, സമർപ്പിക്കുക, അല്ലെങ്കിൽ പൊതു വിവരങ്ങൾ കാണുക.",
  "features.track.title": "ID വഴി ട്രാക്ക് ചെയ്യുക",
  "features.track.desc": "പരാതി ID വഴി തിരയുക, സ്ഥിതി കാണുക: തീർപ്പാകാത്തത്, പ്രക്രിയയിൽ, യോഗം നിശ്ചയിച്ചിട്ടുണ്ട്, അല്ലെങ്കിൽ പൂർത്തിയായി.",
  "features.track.cta": "പരാതി ട്രാക്ക് ചെയ്യുക",
  "features.raise.title": "പരാതി നൽകുക",
  "features.raise.desc": "OTP സ്ഥിരീകരണത്തോടെ സമർപ്പിക്കുക. തലക്കെട്ട്, വിവരണം, സ്ഥലം, ചിത്രങ്ങൾ ചേർക്കുക — അക്കൗണ്ട് ആവശ്യമില്ല.",
  "features.raise.cta": "പരാതി നൽകുക",
  "features.meetings.title": "പൊതു യോഗങ്ങൾ",
  "features.meetings.desc": "യോഗ സംഗ്രഹങ്ങൾ, ജോലി പുരോഗതി, അനുമതി സ്ഥിതി എന്നിവ റീഡ്-ഓൺലി പാരദർശിത്വ മോഡിൽ കാണുക.",
  "features.meetings.cta": "യോഗങ്ങൾ കാണുക",

  // Track page
  "track.title": "പരാതി ട്രാക്ക് ചെയ്യുക",
  "track.hero.desc": "നിലവിലെ സ്ഥിതി കാണാൻ പരാതി ID നൽകുക: തീർപ്പാകാത്തത്, പ്രക്രിയയിൽ, യോഗം നിശ്ചയിച്ചിട്ടുണ്ട്, അല്ലെങ്കിൽ പൂർത്തിയായി.",
  "track.card.title": "പരാതി ID വഴി തിരയുക",
  "track.card.desc": "പരാതി സമർപ്പിച്ചപ്പോൾ ലഭിച്ച ID ഉപയോഗിക്കുക.",
  "track.placeholder": "ഉദാ. C-1245 അല്ലെങ്കിൽ പരാതി ID",
  "track.button": "ട്രാക്ക് ചെയ്യുക",
  "track.process": "പരാതി പ്രക്രിയ",
  "track.location": "സ്ഥലം",
  "track.category": "വിഭാഗം",
  "track.submitted": "സമർപ്പിച്ചു",
  "track.updated": "അപ്ഡേറ്റ് ചെയ്തു",
  "track.step.pending": "തീർപ്പാകാത്തത്",
  "track.step.assigned": "നിയോഗിച്ചു",
  "track.step.inprogress": "പ്രക്രിയയിൽ",
  "track.step.meeting": "യോഗം നിശ്ചയിച്ചിട്ടുണ്ട്",
  "track.step.completed": "പൂർത്തിയായി",
  "track.step.rejected": "നിരസിച്ചു",

  // Raise complaint
  "raise.title": "പരാതി നൽകുക (ലോഗിൻ ഇല്ലാതെ)",
  "raise.hero.desc": "OTP സ്ഥിരീകരിക്കുക, തുടർന്ന് തലക്കെട്ട്, വിവരണം, സ്ഥലം, ഐച്ഛിക ചിത്രങ്ങൾ സമർപ്പിക്കുക.",
  "raise.step1.title": "ഘട്ടം 1: ബന്ധപ്പെടൽ",
  "raise.step1.desc": "OTP ലഭിക്കാൻ ഫോൺ അല്ലെങ്കിൽ ഇമെയിൽ നൽകുക",
  "raise.step2.title": "ഘട്ടം 2: OTP സ്ഥിരീകരിക്കുക",
  "raise.step2.desc": "നിങ്ങൾക്ക് അയച്ച 6-അക്ക കോഡ് നൽകുക",
  "raise.step3.title": "ഘട്ടം 3: പരാതി വിവരങ്ങൾ",
  "raise.step3.desc": "പരാതിയുടെ വിവരങ്ങൾ പൂരിപ്പിക്കുക",
  "raise.label.contact": "ഫോൺ അല്ലെങ്കിൽ ഇമെയിൽ",
  "raise.placeholder.contact": "ഉദാ. 9876543210 അല്ലെങ്കിൽ email@example.com",
  "raise.btn.sendotp": "OTP അയക്കുക",
  "raise.label.otp": "OTP",
  "raise.placeholder.otp": "6-അക്ക കോഡ്",
  "raise.btn.verify": "സ്ഥിരീകരിക്കുക",
  "raise.btn.change": "നമ്പർ/ഇമെയിൽ മാറ്റുക",
  "raise.label.title": "തലക്കെട്ട് *",
  "raise.placeholder.title": "ചുരുക്കിയ തലക്കെട്ട്",
  "raise.label.desc": "വിവരണം *",
  "raise.placeholder.desc": "പ്രശ്നം വിവരിക്കുക",
  "raise.label.location": "സ്ഥലം (വിലാസം അല്ലെങ്കിൽ പ്രദേശം)",
  "raise.placeholder.location": "ഉദാ. ബ്ലോക്ക് A, മെയിൻ റോഡ്",
  "raise.label.category": "വിഭാഗം",
  "raise.label.priority": "മുൻഗണന",
  "raise.label.images": "ചിത്രങ്ങൾ (ഐച്ഛികം, പരമാവധി 5)",
  "raise.btn.addimage": "ചിത്രം ചേർക്കുക",
  "raise.btn.submit": "പരാതി സമർപ്പിക്കുക",
  "raise.success.title": "പരാതി സമർപ്പിച്ചു",
  "raise.success.desc": "പരാതി ട്രാക്ക് ചെയ്യാൻ ഈ ID സൂക്ഷിക്കുക:",
  "raise.success.track": "പരാതി ട്രാക്ക് ചെയ്യുക",

  // Notices
  "notices.title": "നോട്ടീസുകളും അറിയിപ്പുകളും",
  "notices.hero.desc": "മുനിസിപ്പാലിറ്റിയിൽ നിന്നുള്ള ഔദ്യോഗിക നോട്ടീസുകളും അപ്ഡേറ്റുകളും.",
  "notices.empty": "ഇപ്പോൾ നോട്ടീസുകൾ ഇല്ല.",
  "notices.error": "നോട്ടീസുകൾ ലോഡ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു.",
  "notices.viewpdf": "PDF കാണുക",

  // Transparency
  "transparency.title": "പാരദർശിത്വ ഡാഷ്ബോർഡ്",
  "transparency.hero.desc": "പ്രദേശം-തിരിച്ചും വകുപ്പ് പ്രകടനവും. പൊതു കാഴ്ച — ലോഗിൻ ആവശ്യമില്ല.",
  "transparency.stat.total": "മൊത്തം പരാതികൾ",
  "transparency.stat.completed": "പൂർത്തിയായി",
  "transparency.stat.pending": "തീർപ്പാകാത്തത്",
  "transparency.stat.rate": "പരിഹാര നിരക്ക്",
  "transparency.chart.title": "വിഭാഗം (പ്രദേശം) അനുസരിച്ച് പരാതികൾ",
  "transparency.chart.desc": "പാരദർശിത്വത്തിനായുള്ള വിതരണം",
  "transparency.chart.empty": "ഇനിയും ഡേറ്റ ഇല്ല",
  "transparency.recent.title": "സമീപകാല പ്രവർത്തനം",
  "transparency.recent.desc": "ഏറ്റവും പുതിയ പരാതി അപ്ഡേറ്റുകൾ",
  "transparency.recent.empty": "ഇനിയും പരാതികൾ ഇല്ല.",

  // Footer
  "footer.brand.desc": "സ്മാർട്ട് മുനിസിപ്പൽ പരാതി & യോഗ നിയന്ത്രണം — നിങ്ങളുടെ സമൂഹത്തിൽ പാരദർശിത്വവും കാര്യക്ഷമമായ പൗര സേവനങ്ങളും.",
  "footer.quicklinks": "ദ്രുത ലിങ്കുകൾ",
  "footer.contact": "ഞങ്ങളെ ബന്ധപ്പെടുക",
  "footer.hours.title": "ഓഫീസ് സമയം",
  "footer.hours.weekday": "തിങ്കൾ – ശനി: രാവിലെ 10:00 – വൈകുന്നേരം 5:00",
  "footer.hours.weekend": "ഞായർ & അവധി ദിവസങ്ങൾ: അടഞ്ഞിരിക്കും",
  "footer.holidays": "അവധി കലണ്ടർ",
  "footer.holiday.note": "സംസ്ഥാന സർക്കാർ ഉത്തരവുകൾ അനുസരിച്ച് അവധി ദിവസങ്ങൾ.",
  "footer.holiday.public": "പൊതു അവധി",
  "footer.holiday.weekly": "വാരാന്ത്യ അവധി",
  "footer.holiday.list": "അവധി പട്ടിക",
  "footer.rights": "എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം.",
  "footer.noauth": "പരാതി ട്രാക്കിംഗ് & സമർപ്പണത്തിന് ലോഗിൻ ആവശ്യമില്ല.",
  "footer.link.home": "ഹോം",
  "footer.link.track": "പരാതി ട്രാക്ക് ചെയ്യുക",
  "footer.link.raise": "പരാതി നൽകുക",
  "footer.link.transparency": "പാരദർശിത്വ പോർട്ടൽ",
  "footer.link.meetings": "പൊതു യോഗങ്ങൾ",
  "footer.link.notices": "നോട്ടീസുകൾ",

  // Dashboard
  "dash.dashboard": "ഡാഷ്ബോർഡ്",
  "dash.complaints": "പരാതികൾ",
  "dash.meetings": "യോഗങ്ങൾ",
  "dash.tasks": "ജോലികൾ",
  "dash.bills": "ബില്ലുകൾ",
  "dash.payments": "പേയ്മെന്റുകൾ",
  "dash.departments": "വകുപ്പുകൾ",
  "dash.staff": "സ്റ്റാഫ്",
  "dash.notifications": "നോട്ടീസുകൾ",
  "dash.reports": "റിപ്പോർട്ടുകൾ",
  "dash.audit": "ഓഡിറ്റ്",
  "dash.projects": "പ്രോജക്ടുകൾ",
  "dash.notices": "നോട്ടീസ് മാനേജ്മെന്റ്",
  "dash.profile": "പ്രൊഫൈൽ",
  "dash.logout": "ലോഗ് ഔട്ട്",
  "dash.search": "പരാതികൾ, ജോലികൾ, യോഗങ്ങൾ തിരയുക...",
  "dash.notifications.label": "നോട്ടീസുകൾ",
  "dash.switchrole": "റോൾ മാറ്റുക (ഡെമോ)",
  "dash.myprofile": "എന്റെ പ്രൊഫൈൽ",
};

/* ─────────────────────────────────────────────────────────────
   All Translations
───────────────────────────────────────────────────────────── */
const translations: Record<Language, Record<string, string>> = {
  en,
  gu,
  hi,
  mr,
  ta,
  te,
  bn,
  pa,
  kn,
  ml,
};